{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-gson",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "fcwrn35ki5gbhpoo22hcetvtz4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "nova-gson-edge.jar",
          "url": "nova-gson-edge.jar",
          "size": 12327,
          "sha512": "5b6d8d29614b98e8ae1164f7537c36171eaeac3a18cff34d27fc4132e04529e1d3762489bb3f123e57fbd6ea8494fdce0d6f57549b5f84cf16bb76823ab97cbd",
          "sha256": "d2ad6baca9a651c71830535ac6549facc2054d29c4c73abfa9e27784c29be784",
          "sha1": "9f538c21b53e322f7f192319d49e006ffb864738",
          "md5": "210f2ab55c6852f527affc4a491ccd26"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "nova-gson-edge.jar",
          "url": "nova-gson-edge.jar",
          "size": 12327,
          "sha512": "5b6d8d29614b98e8ae1164f7537c36171eaeac3a18cff34d27fc4132e04529e1d3762489bb3f123e57fbd6ea8494fdce0d6f57549b5f84cf16bb76823ab97cbd",
          "sha256": "d2ad6baca9a651c71830535ac6549facc2054d29c4c73abfa9e27784c29be784",
          "sha1": "9f538c21b53e322f7f192319d49e006ffb864738",
          "md5": "210f2ab55c6852f527affc4a491ccd26"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-gson-edge-javadoc.jar",
          "url": "nova-gson-edge-javadoc.jar",
          "size": 136977,
          "sha512": "4b3408d2a2f2054025f4a8041cb7e7f7e5e9d1fc4a9cf6be1eaef832d8765e0eaa95fe7adc919fa88b89833c5bc38f8a95efb7bc428d747d1471cb32fdbb2909",
          "sha256": "fe1f615ae8361f1e10c49610f9d8a1ba1617a828e92ea0b9c92b2c30c596d64d",
          "sha1": "a85a5761dbac3758c9272bb023a86a4eb59645a8",
          "md5": "468b6bbac05e9db942d40db52ed998bc"
        }
      ]
    }
  ]
}
