{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-gson",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "bcc5ymcgxfam7evbluga3yp4ia"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "nova-gson-edge.jar",
          "url": "nova-gson-edge.jar",
          "size": 12252,
          "sha512": "bb2278389d9c9aef30ecd0b5764955ec849809d46d9a0cbae95c8ab5c7ca5c28fc8bdfc2d4378e358740c78ba02af2e68ce5573227ad9ed65c24fe3e64165f38",
          "sha256": "4cdde7e0e1688add1bf57e133bbeb58542efd3f001c30aa1cd9840f59c649d80",
          "sha1": "9d0b6dc2df0f1f3d50e63dc27b69a960b9cbdcb7",
          "md5": "d6896747744914f0336cf778b8fec366"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "nova-gson-edge.jar",
          "url": "nova-gson-edge.jar",
          "size": 12252,
          "sha512": "bb2278389d9c9aef30ecd0b5764955ec849809d46d9a0cbae95c8ab5c7ca5c28fc8bdfc2d4378e358740c78ba02af2e68ce5573227ad9ed65c24fe3e64165f38",
          "sha256": "4cdde7e0e1688add1bf57e133bbeb58542efd3f001c30aa1cd9840f59c649d80",
          "sha1": "9d0b6dc2df0f1f3d50e63dc27b69a960b9cbdcb7",
          "md5": "d6896747744914f0336cf778b8fec366"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-gson-edge-javadoc.jar",
          "url": "nova-gson-edge-javadoc.jar",
          "size": 426543,
          "sha512": "5ee4c9dc890f09c0d7f295647ccc970a645b51b2f7e4e7c2a536b7b35b6fc0b8b82c4f7d999488d9cf93230d7f16b1659f99f8491936d1371a1c8e9dcf78edc5",
          "sha256": "ced9ea938ea650fa6d5cd64da15aecc2ea416ae20d29891931f12b6012c4aa33",
          "sha1": "2c7efba3d8f50221e09cdd607b5a587e6181fe0d",
          "md5": "6b95c14af3883259146021b56acd802f"
        }
      ]
    }
  ]
}
