{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-gson",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "c2ghcfclmra75c7f2b6nkugooe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "nova-gson-edge.jar",
          "url": "nova-gson-edge.jar",
          "size": 12332,
          "sha512": "c5c689d74fea5ca90f86e64595213f88bdc6a51812458e5c9c1ec205e146c3a982a59f400b33ae7e7144d0a30c85ea9206ac64e7ac622858de35dc93d6ddef49",
          "sha256": "06911fb4649ea9ab0b8f73222d9c4e609d4c3c4e10eecab3c60c1aefafb102b8",
          "sha1": "2ba104cd20fbe9ae8abbec656abaf19ec120dc77",
          "md5": "8d61cf1df02d22461404c26f97210159"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "nova-gson-edge.jar",
          "url": "nova-gson-edge.jar",
          "size": 12332,
          "sha512": "c5c689d74fea5ca90f86e64595213f88bdc6a51812458e5c9c1ec205e146c3a982a59f400b33ae7e7144d0a30c85ea9206ac64e7ac622858de35dc93d6ddef49",
          "sha256": "06911fb4649ea9ab0b8f73222d9c4e609d4c3c4e10eecab3c60c1aefafb102b8",
          "sha1": "2ba104cd20fbe9ae8abbec656abaf19ec120dc77",
          "md5": "8d61cf1df02d22461404c26f97210159"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-gson-edge-javadoc.jar",
          "url": "nova-gson-edge-javadoc.jar",
          "size": 136985,
          "sha512": "d4278692e5bde4e9b57d7323745d62944cec78124a7ea715a782138fc88a5dc879b0bdbf4be1c467a8962ae90d9015061325129d16c5f22aa5819f7a5ba14039",
          "sha256": "6136426675f5e9cdf4556b4aa8aa48cc094f748aa642d5827ba5c31c94727579",
          "sha1": "8a56bb128b55fa9834bea889638f578fc06abe32",
          "md5": "225ae22480b49dcf5f716cc79bd1b7f8"
        }
      ]
    }
  ]
}
