{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-influx",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nova-influx-edge.jar",
          "url": "nova-influx-edge.jar",
          "size": 45026,
          "sha512": "fd482c7902b2ec4c622c85ba1a5c0ec1bdc1c0b243638f7e3d8aef976e0c9a85700af3ec009d7345cf706aff4163fc85d889cba447102e1297c02c74ce6a0bd8",
          "sha256": "191d998caf5e398b9786ad16d4549662a20124fcab7efe5339124315ac656a4c",
          "sha1": "0bc004337b62e4ba05a8c531687bff480f367ef3",
          "md5": "33eeecf494a27069c5fb118bb9614d0a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "2.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "nova-influx-edge.jar",
          "url": "nova-influx-edge.jar",
          "size": 45026,
          "sha512": "fd482c7902b2ec4c622c85ba1a5c0ec1bdc1c0b243638f7e3d8aef976e0c9a85700af3ec009d7345cf706aff4163fc85d889cba447102e1297c02c74ce6a0bd8",
          "sha256": "191d998caf5e398b9786ad16d4549662a20124fcab7efe5339124315ac656a4c",
          "sha1": "0bc004337b62e4ba05a8c531687bff480f367ef3",
          "md5": "33eeecf494a27069c5fb118bb9614d0a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-influx-edge-javadoc.jar",
          "url": "nova-influx-edge-javadoc.jar",
          "size": 456062,
          "sha512": "059a2b8d13ae97ad12db77e765ef4216c676829def32fbdd9bd698746d5d8c401435af970da56de56853ed65bf1403a1943301b54c89b2b13e9a42ec6a7e620e",
          "sha256": "853591189456c9fb3431e41a28ae0786ffab8512e69fda2ce3d917a21af77953",
          "sha1": "7bd2493ae7553496586acb0a2fc2028c499d70ec",
          "md5": "3942f63ef7d920876638af2d887d9ee9"
        }
      ]
    }
  ]
}
