{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-influx",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nova-influx-edge.jar",
          "url": "nova-influx-edge.jar",
          "size": 45052,
          "sha512": "9ad91aac831be629b52ccf51cc1e3cfe702fbff47ee43f3756e1f00b336ed616c60ccd564446ff871761c09c6b1fa05da35ac3dc094a2e6df0716fce0707b2fb",
          "sha256": "2af1559ee2b6b521a2dd44fa2c07ee024f5ffffe30bc390208329f596ef42f55",
          "sha1": "fdd82c051741f7e79c79a0a819e4e94fa4ab5797",
          "md5": "cf028a8cbe94b1bb3e6550218a4290a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "2.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "nova-influx-edge.jar",
          "url": "nova-influx-edge.jar",
          "size": 45052,
          "sha512": "9ad91aac831be629b52ccf51cc1e3cfe702fbff47ee43f3756e1f00b336ed616c60ccd564446ff871761c09c6b1fa05da35ac3dc094a2e6df0716fce0707b2fb",
          "sha256": "2af1559ee2b6b521a2dd44fa2c07ee024f5ffffe30bc390208329f596ef42f55",
          "sha1": "fdd82c051741f7e79c79a0a819e4e94fa4ab5797",
          "md5": "cf028a8cbe94b1bb3e6550218a4290a7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-influx-edge-javadoc.jar",
          "url": "nova-influx-edge-javadoc.jar",
          "size": 456014,
          "sha512": "107f5f043962a4fdf135ebdb4b12f0bcde2935e59d018f37731ffb61ce53a8bafbdb4461eb2154bcdd29cee714e3d05e6fae7e800b6727969f1ea5e598983acd",
          "sha256": "b09051c2b624288150e7ca2561fa99091d516ab6801854061c58da87897b4a10",
          "sha1": "f62b412304b64ae143925e6a00489594aee3c84e",
          "md5": "7c53a4dace8a24a182545074cd589196"
        }
      ]
    }
  ]
}
