{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-influx",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nova-influx-edge.jar",
          "url": "nova-influx-edge.jar",
          "size": 46403,
          "sha512": "2aa69dd80d30306891e8427b094c6aa3a21a81a61232e8fb5a21288f543b762e59b38e708d17c34d1b0bdbf3a7178fd1d91bb528e11bf935ab63bc9275ae75df",
          "sha256": "d78903752b073272bb92624efa54e7b5f3ffe162a5d4918119ae25e7f084a21c",
          "sha1": "5185e7cdda317a0ecb68f2cbdd0027a8488ef98e",
          "md5": "d38943f4cf0cf1914ad62c7b56afac21"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "2.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "nova-influx-edge.jar",
          "url": "nova-influx-edge.jar",
          "size": 46403,
          "sha512": "2aa69dd80d30306891e8427b094c6aa3a21a81a61232e8fb5a21288f543b762e59b38e708d17c34d1b0bdbf3a7178fd1d91bb528e11bf935ab63bc9275ae75df",
          "sha256": "d78903752b073272bb92624efa54e7b5f3ffe162a5d4918119ae25e7f084a21c",
          "sha1": "5185e7cdda317a0ecb68f2cbdd0027a8488ef98e",
          "md5": "d38943f4cf0cf1914ad62c7b56afac21"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-influx-edge-javadoc.jar",
          "url": "nova-influx-edge-javadoc.jar",
          "size": 456071,
          "sha512": "ae33deb9ad4460cfe4fa51e321b1449e14ba28ea02a9b0a2460944a400cd35689b8d289dfca4cd4054b5becec2c8c880d57db51ba97480fcecb774b54473147b",
          "sha256": "4981231b7cd4a412e397789a30b094339806806e72aa94622a848a45f7a8f377",
          "sha1": "c27561c783c230507913dad01da46115c1cb4389",
          "md5": "79ca84ddcb6d75aa3d130324d0fd3205"
        }
      ]
    }
  ]
}
