{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-api",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6hn2zdnvezdijfuhzyxec5uquu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "jakarta.validation",
          "module": "jakarta.validation-api",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.4"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-core",
          "version": {
            "requires": "edge"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-web",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-api-edge.jar",
          "url": "nova-api-edge.jar",
          "size": 74555,
          "sha512": "5b62a27d19d71d47361c9cd57330b72beaa2869459c596fb7bb79dd591f451f405193789cbcc52e748e9576a65d5fa39ee8e747c421c2a08db178322e6a80310",
          "sha256": "b18eb0e15629372e08435bf82d43e53bafe4c1c4da04b88df5f476221d9929f6",
          "sha1": "29f760d820db0a2bc7d0d90c060bf5e2402c9bea",
          "md5": "b4eb75a6b613ede5e4a37d16d86e4fab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "jakarta.validation",
          "module": "jakarta.validation-api",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.4"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-core",
          "version": {
            "requires": "edge"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-web",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-api-edge.jar",
          "url": "nova-api-edge.jar",
          "size": 74555,
          "sha512": "5b62a27d19d71d47361c9cd57330b72beaa2869459c596fb7bb79dd591f451f405193789cbcc52e748e9576a65d5fa39ee8e747c421c2a08db178322e6a80310",
          "sha256": "b18eb0e15629372e08435bf82d43e53bafe4c1c4da04b88df5f476221d9929f6",
          "sha1": "29f760d820db0a2bc7d0d90c060bf5e2402c9bea",
          "md5": "b4eb75a6b613ede5e4a37d16d86e4fab"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-api-edge-javadoc.jar",
          "url": "nova-api-edge-javadoc.jar",
          "size": 519902,
          "sha512": "70af706b5953a033312ba778cd7839cdd281a0227c3fcd05f9f88c85485257c682222c1889c627dba3232bbc829105a26afe36b82becd4ae5d213a5c9cc2e532",
          "sha256": "9f530c2557a659d852327499464dec8b16ea9d8fcff70f06e29b202df34bc186",
          "sha1": "27d088f43cd9e71d66d5042a166880048d8ddf5e",
          "md5": "c1882c983485c30738b3d1286b1cfee7"
        }
      ]
    }
  ]
}
