{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-api",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "bcc5ymcgxfam7evbluga3yp4ia"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-gson",
          "version": {
            "requires": "edge"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-network",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-api-edge.jar",
          "url": "nova-api-edge.jar",
          "size": 52501,
          "sha512": "4948e910497183552ed22e87b9a94814607e944fb4523f076cf562c898d92e630ef2ec844acb4256d322f2e0c770effa067eb73b88795a3000fc4175bc602f58",
          "sha256": "150b95ecdd8b5668958286716fa034dec70cf04b248c3c155fdb7e2f61714aca",
          "sha1": "8f8ea87f95a72e12355fde77cf7e2872956893c1",
          "md5": "d57b27055f8d7d0aaa58418262c5a0da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-gson",
          "version": {
            "requires": "edge"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-network",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-api-edge.jar",
          "url": "nova-api-edge.jar",
          "size": 52501,
          "sha512": "4948e910497183552ed22e87b9a94814607e944fb4523f076cf562c898d92e630ef2ec844acb4256d322f2e0c770effa067eb73b88795a3000fc4175bc602f58",
          "sha256": "150b95ecdd8b5668958286716fa034dec70cf04b248c3c155fdb7e2f61714aca",
          "sha1": "8f8ea87f95a72e12355fde77cf7e2872956893c1",
          "md5": "d57b27055f8d7d0aaa58418262c5a0da"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-api-edge-javadoc.jar",
          "url": "nova-api-edge-javadoc.jar",
          "size": 508628,
          "sha512": "b88789697f3411cd7bcde86791c1472ed5e05aec030458d8408f8c7eab2f5b00db49d74221a0d0432d3d8fd15f1a58a16c59235bd0ae617487426ec5089b89ce",
          "sha256": "3d0e1d1f25a242f0627f2cdbb3849965428bccc92ca8c1063bfac7a729bcfbe9",
          "sha1": "b21b77714315aac99fbb96eee515456edc98a81e",
          "md5": "36b5a16cf638aa07822e698180af6c61"
        }
      ]
    }
  ]
}
