{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-api",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "etplgg6ugrad7my6bf35r3hdia"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "jakarta.validation",
          "module": "jakarta.validation-api",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.4"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-core",
          "version": {
            "requires": "edge"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-web",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-api-edge.jar",
          "url": "nova-api-edge.jar",
          "size": 74551,
          "sha512": "350492d3942727ca59eeb44ed87141320debef62d86f74d44aac3c8ea3d363e13b4ce55c29d2951dab10f42d8f326ac7399274911e8910c48940bb66bb943f52",
          "sha256": "c74485d3a2255cc7ef0f3f7df2a1df8bbf0abfeffdd1557e5274a544a9c58715",
          "sha1": "4c8d102aa22636f1a8eb8a026c37fe60c7d199e8",
          "md5": "8131fd86745c54a496c243789a6ab69b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "jakarta.validation",
          "module": "jakarta.validation-api",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.4"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-core",
          "version": {
            "requires": "edge"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-web",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-api-edge.jar",
          "url": "nova-api-edge.jar",
          "size": 74551,
          "sha512": "350492d3942727ca59eeb44ed87141320debef62d86f74d44aac3c8ea3d363e13b4ce55c29d2951dab10f42d8f326ac7399274911e8910c48940bb66bb943f52",
          "sha256": "c74485d3a2255cc7ef0f3f7df2a1df8bbf0abfeffdd1557e5274a544a9c58715",
          "sha1": "4c8d102aa22636f1a8eb8a026c37fe60c7d199e8",
          "md5": "8131fd86745c54a496c243789a6ab69b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-api-edge-javadoc.jar",
          "url": "nova-api-edge-javadoc.jar",
          "size": 519892,
          "sha512": "8ca04eecbf73926d3f79887df95dbd8b9bf53b28ba64d9c3827a3d7f05dc7ce92f53252dd48af4449946075e6aa4af3b0072a834a2d5809a9f8849b9d774a10b",
          "sha256": "3e83143478dd04340c35ed2ee153126f97c8ec7bb84224713653b12a57f31da6",
          "sha1": "8a595106e838e631422cb5a351ea496acb0f0d19",
          "md5": "700b5eae3691cb72327b80a8183b45a4"
        }
      ]
    }
  ]
}
