{
  "formatVersion": "1.1",
  "component": {
    "group": "de.m4rc3l.nova",
    "module": "nova-influx",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "2.6.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "2.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "nova-influx-edge.jar",
          "url": "nova-influx-edge.jar",
          "size": 44990,
          "sha512": "47687b1d0d3ad5abe8858d51fc00db029733bcc67ccd5aa5c42baa0c78fda2500b05f2b19d368611e181640b8e31954289b175ec4ba95ddc5cf338f9db64eb16",
          "sha256": "d67b9b9cd0414e54212e897ce6858a740499e66a1a4175ca8499bf62e877c81a",
          "sha1": "c37fda3691553bbc0d7655cfb59aceff435e5e9e",
          "md5": "4a11954c0a127a09c447e30f60d5123c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "2.6.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "2.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "nova-influx-edge.jar",
          "url": "nova-influx-edge.jar",
          "size": 44990,
          "sha512": "47687b1d0d3ad5abe8858d51fc00db029733bcc67ccd5aa5c42baa0c78fda2500b05f2b19d368611e181640b8e31954289b175ec4ba95ddc5cf338f9db64eb16",
          "sha256": "d67b9b9cd0414e54212e897ce6858a740499e66a1a4175ca8499bf62e877c81a",
          "sha1": "c37fda3691553bbc0d7655cfb59aceff435e5e9e",
          "md5": "4a11954c0a127a09c447e30f60d5123c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-influx-edge-javadoc.jar",
          "url": "nova-influx-edge-javadoc.jar",
          "size": 182512,
          "sha512": "83f58ff245db3f5035c8ce9e9783b8d63f5402bc870c30ad3bc67b81616451214dd78f28a48cf9cc3774725d2759bd50201edf3dd527ff3ff48ab4caacfe48c6",
          "sha256": "90d9a7a6a459c30904b0d35c87d53a418ac2fcfc70842e07f47e5531b974a3a8",
          "sha1": "165ddb8e23d46872385bf70faf1439f88fea786c",
          "md5": "5eb61b80c03399091b5a00bf62481cf3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-influx-edge-sources.jar",
          "url": "nova-influx-edge-sources.jar",
          "size": 9631,
          "sha512": "719a356104ac843680d03637ba0a930fcfe84a6b45e89284c55ef8ce314a1bd3e13e91d42985cee73b1e2c902d7e5d550e78359db9bbbe08ea79fb83976b8bb0",
          "sha256": "2479ee12871c0e86c93e12c437f6eccb10e1276b54743a32674ba09680ff8737",
          "sha1": "ab2e19213d74b12df98448c953f3816ca59d8630",
          "md5": "a8facd6df05eef928132dab4f5033d3f"
        }
      ]
    }
  ]
}
