{
  "formatVersion": "1.1",
  "component": {
    "group": "de.m4rc3l.nova",
    "module": "nova-influx",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "2.6.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "2.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "nova-influx-edge.jar",
          "url": "nova-influx-edge.jar",
          "size": 44976,
          "sha512": "b20107a6f7d824d290160c2e9fe66aceae58b5f579eb33bec7801eb2b5543526bef34bc1fd3be0255476309776e4b6626349466c576c63970c0fded0e8c6c43d",
          "sha256": "fa020d5379b75142577b21cfc4586758565a1248c7e6313c95a303c17eb49c8c",
          "sha1": "04a1613d1e6ed74b6a41941fc3f50182b62c2705",
          "md5": "180fb36a9e29c640d2278fa9172ddcfd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "2.6.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "2.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "nova-influx-edge.jar",
          "url": "nova-influx-edge.jar",
          "size": 44976,
          "sha512": "b20107a6f7d824d290160c2e9fe66aceae58b5f579eb33bec7801eb2b5543526bef34bc1fd3be0255476309776e4b6626349466c576c63970c0fded0e8c6c43d",
          "sha256": "fa020d5379b75142577b21cfc4586758565a1248c7e6313c95a303c17eb49c8c",
          "sha1": "04a1613d1e6ed74b6a41941fc3f50182b62c2705",
          "md5": "180fb36a9e29c640d2278fa9172ddcfd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-influx-edge-javadoc.jar",
          "url": "nova-influx-edge-javadoc.jar",
          "size": 182502,
          "sha512": "0288a27a71f547a64e91b6217d8c311cf2b2bfbf085ca17e9045c1a07c2ccdba1279ac58f9fb657c210478139bc691e25416ec6790ad98eab7ef28f0ac16f128",
          "sha256": "0819ad483f8ce8772573a75676a6eb83a9502e9670a18a3589bef4fdf1191f5f",
          "sha1": "c5e599ed06ba2dad0e5b23a6dbf92b9c8feb6d6f",
          "md5": "0c21cfff0597acc7ab05b5fca9c87f7c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-influx-edge-sources.jar",
          "url": "nova-influx-edge-sources.jar",
          "size": 9621,
          "sha512": "92c27b7b90216241a23887c7d993d6e2955964d4553026516f53679379f9c572dae6b9e1624614d1b6c4a248bb07503eb71d562bf2ebba8644e4f54312981c71",
          "sha256": "16be2fcb1626bf501eaa978082ea5a78e8367c0f2bacf370f841c98d4dcebff0",
          "sha1": "5e72852070b364454c14bfdaaaa0a3ec2cfa1b13",
          "md5": "ffb5eb380ab481db7293216dad81978f"
        }
      ]
    }
  ]
}
