{
  "formatVersion": "1.1",
  "component": {
    "group": "de.m4rc3l.nova",
    "module": "nova-influx",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "2.6.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "2.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "nova-influx-edge.jar",
          "url": "nova-influx-edge.jar",
          "size": 44986,
          "sha512": "48ce49db70fde005baadf57c04157941ebb7490b5cad626d9f770529d65304d6c791f1cdd645eddae3bddbe0232012e3c983557db156bf3eed627a78ba35d592",
          "sha256": "b772a04785b4a1898fcd208bf02bf7667fe8e7fa4ae2ccce6da58a2dec78bc73",
          "sha1": "7020a1467fb60da37ce608053ea6b91ebe4fd296",
          "md5": "ab84dc760ec355abfbf60012d4724ae9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "2.6.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "2.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "nova-influx-edge.jar",
          "url": "nova-influx-edge.jar",
          "size": 44986,
          "sha512": "48ce49db70fde005baadf57c04157941ebb7490b5cad626d9f770529d65304d6c791f1cdd645eddae3bddbe0232012e3c983557db156bf3eed627a78ba35d592",
          "sha256": "b772a04785b4a1898fcd208bf02bf7667fe8e7fa4ae2ccce6da58a2dec78bc73",
          "sha1": "7020a1467fb60da37ce608053ea6b91ebe4fd296",
          "md5": "ab84dc760ec355abfbf60012d4724ae9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-influx-edge-javadoc.jar",
          "url": "nova-influx-edge-javadoc.jar",
          "size": 182512,
          "sha512": "06056a8e538ba787f94d98efdf745edbb1aeeacc5302cfae5a0a0bf929ccb905b8ec9c6dc1954eed9d016deb2d0594aa4c1fe18401be71e8dcc8620bc0e50a33",
          "sha256": "29e1f823222376b19b7e04fd16947972608435ad0c87f15d81138ad44a4eca2c",
          "sha1": "2ffeb912d50d7e197b03baf7c17a7045373b1f77",
          "md5": "07473f6ff1ed5b84b5ba90b9eedf13a8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-influx-edge-sources.jar",
          "url": "nova-influx-edge-sources.jar",
          "size": 9631,
          "sha512": "332b34f67d1259ec5db4074eecd98733000a5b670da3549b70942cd91ba3b48bc7c4e1ab96ce67dbf080a0bfa7db51f2a1ac7cb59d668d5a23fd57431fd7bb80",
          "sha256": "379b70a6b531789bf9f85b220843a0ed9714bf72698070b551c160d6e4c83837",
          "sha1": "63c411d65f4f2e04e2230b35a7d1c31f019ebcc4",
          "md5": "b8c2e7a5924f34033889a435f8c80549"
        }
      ]
    }
  ]
}
