{
  "formatVersion": "1.1",
  "component": {
    "group": "de.m4rc3l.nova",
    "module": "nova-core",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        }
      ],
      "files": [
        {
          "name": "nova-core-edge.jar",
          "url": "nova-core-edge.jar",
          "size": 44095,
          "sha512": "11b4ed8e951d671e30782e0cc97433aff0929c7a190dcd496eca06eae7b4ce5fc659ab62005cc1964593d1de1cbca332bbf610a2cf86e0e80318e41dc9762752",
          "sha256": "b6a7e484d0647710794d9cdbf3f73744e47d103f4962d1794f7f24ae48d2d331",
          "sha1": "aa46d538d0f0c8b0a505c7cf765ac2aeb27db556",
          "md5": "635aeec4e949a9b9778bf24a4b6eb572"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        }
      ],
      "files": [
        {
          "name": "nova-core-edge.jar",
          "url": "nova-core-edge.jar",
          "size": 44095,
          "sha512": "11b4ed8e951d671e30782e0cc97433aff0929c7a190dcd496eca06eae7b4ce5fc659ab62005cc1964593d1de1cbca332bbf610a2cf86e0e80318e41dc9762752",
          "sha256": "b6a7e484d0647710794d9cdbf3f73744e47d103f4962d1794f7f24ae48d2d331",
          "sha1": "aa46d538d0f0c8b0a505c7cf765ac2aeb27db556",
          "md5": "635aeec4e949a9b9778bf24a4b6eb572"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-core-edge-javadoc.jar",
          "url": "nova-core-edge-javadoc.jar",
          "size": 175673,
          "sha512": "eca5990b6498d55c877fc8433938b8da917b6b1c36abd617b200b0392abe7f999aa64bb0d280478f9d660d6ff2aae6c4ce8945768e762bb6cc1862cbea5482e2",
          "sha256": "1e94ee71eaf6492a82e368212e53916b63bc373ff958d10e2c32dbedfb0c977a",
          "sha1": "1755b0bdde3b0453b73fc3bd9325c567aaafd95f",
          "md5": "b08db712201eda73509be076b25e7ef7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-core-edge-sources.jar",
          "url": "nova-core-edge-sources.jar",
          "size": 17378,
          "sha512": "a00dae218256d756c5a42e406858d4c21804cdb7623b7ad994a6766954260198ca0c914a20064cd6be2d7596619eaad39d661ad9b4b89a1584e00220318f0241",
          "sha256": "1e1b421c1de1d8993ecaaeb57f65092de03a2a1dcd4ead35abeed048addd087a",
          "sha1": "d02677e351f5c13080558697056fba5a0891bdf0",
          "md5": "c8ab4d9ba700d0e1d6a2ea50566bce26"
        }
      ]
    }
  ]
}
