{
  "formatVersion": "1.1",
  "component": {
    "group": "de.m4rc3l.nova",
    "module": "nova-core",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.3"
          }
        }
      ],
      "files": [
        {
          "name": "nova-core-edge.jar",
          "url": "nova-core-edge.jar",
          "size": 44091,
          "sha512": "6a65b5ef3cca9973a2380111e9ec2c85039c65e74e07198115d7da33e71e37271151b57d34c088bec0b4530326aca5a1dcf5342e4ac29a94b34e70095c475192",
          "sha256": "21191650214dfe58a8b18f7c9b24d07581913252d7c5006f0f5028682e6eff3d",
          "sha1": "ad48dd059f12a4b9cc847177c353f719820946af",
          "md5": "6882b739e13338eb82205800c7c2f533"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.3"
          }
        }
      ],
      "files": [
        {
          "name": "nova-core-edge.jar",
          "url": "nova-core-edge.jar",
          "size": 44091,
          "sha512": "6a65b5ef3cca9973a2380111e9ec2c85039c65e74e07198115d7da33e71e37271151b57d34c088bec0b4530326aca5a1dcf5342e4ac29a94b34e70095c475192",
          "sha256": "21191650214dfe58a8b18f7c9b24d07581913252d7c5006f0f5028682e6eff3d",
          "sha1": "ad48dd059f12a4b9cc847177c353f719820946af",
          "md5": "6882b739e13338eb82205800c7c2f533"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-core-edge-javadoc.jar",
          "url": "nova-core-edge-javadoc.jar",
          "size": 175669,
          "sha512": "f072409494b6cf45bb483e55045bfb4f7aca4f5eff788ae9be07639d9b47525e4363dd8b64d82dd59bdb04768abec2ed865d0a21c57c488b19b515d42529403a",
          "sha256": "7c33634b7da57317e34a3b429109bd69d236c4a7bb3a5f38d327bce75365f630",
          "sha1": "67db756fb211528cf5a1b95d4d2dea6da38e8bbb",
          "md5": "459e36aeb364d580a0cabdb1ef2ede16"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-core-edge-sources.jar",
          "url": "nova-core-edge-sources.jar",
          "size": 17373,
          "sha512": "0d142ad9442a5d5ba14c3f1658eb435991d8682558e4501275a0177c36442529202ea9832a2a1ba2bb1befa8ae38230423cf23cc63d6311eca0e3cd9f8d40f56",
          "sha256": "9136410828eeefa92fa223dc9b11482f52348255b9088192b8d31e5139ba9245",
          "sha1": "c52fab8cdf77f04ac654f572f4f0c68cd53ca5b3",
          "md5": "effae92ffe3b8aa405b8502ec8cfb4ed"
        }
      ]
    }
  ]
}
