{
  "formatVersion": "1.1",
  "component": {
    "group": "de.m4rc3l.nova",
    "module": "nova-core",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "nova-core-edge.jar",
          "url": "nova-core-edge.jar",
          "size": 43750,
          "sha512": "5323d1c3ccc18da401c4d7b1d4207ea02cd7eb4ec8fabde592beb2e524f1ed04b899fa3ee126bb6246f69e3a602e0913fd9f3ae2f9766f5e83b80b343e929330",
          "sha256": "aa8bd4c96804be888c61585e857b2272a102025b7677edc6d4e13f5640e9901d",
          "sha1": "accd82fe7a72da339bf6f5d9036e7cfdc95f7c79",
          "md5": "96025a3828eaac1e126fbfc59c4bb326"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "nova-core-edge.jar",
          "url": "nova-core-edge.jar",
          "size": 43750,
          "sha512": "5323d1c3ccc18da401c4d7b1d4207ea02cd7eb4ec8fabde592beb2e524f1ed04b899fa3ee126bb6246f69e3a602e0913fd9f3ae2f9766f5e83b80b343e929330",
          "sha256": "aa8bd4c96804be888c61585e857b2272a102025b7677edc6d4e13f5640e9901d",
          "sha1": "accd82fe7a72da339bf6f5d9036e7cfdc95f7c79",
          "md5": "96025a3828eaac1e126fbfc59c4bb326"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-core-edge-javadoc.jar",
          "url": "nova-core-edge-javadoc.jar",
          "size": 492855,
          "sha512": "0ccf406f9ce71a095c70196c8623774218f7499fa2cb2c0362ab2151bb2fa0ea634451e3a3b6d4cba3fa2beb0834473661c61ee29dc181f8b662cae7c4cf9d00",
          "sha256": "bdcda39e77e7ef4125cf62d8461c6788a009d12c53a00da017b877a5677be972",
          "sha1": "769adabc3eaaea4e2a3388e3badf73bccffed7e3",
          "md5": "e1f93b953b1b9ceb3f1229c41714bdfd"
        }
      ]
    }
  ]
}
