{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework.legacy",
    "module": "nova-api",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.getnova.framework.legacy",
          "module": "nova-boot",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "net.getnova.framework.legacy",
          "module": "nova-json",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "net.getnova.framework.legacy",
          "module": "nova-network",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "nova-api-2.0.1.jar",
          "url": "nova-api-2.0.1.jar",
          "size": 54766,
          "sha512": "c9c4b9aeba0b3ea0f3f52b79089264d092c3ff1299014967cc47484a91fb9d2f571bd207376988d45fd2e896db2fe2214fdecfc2c5b265d2ab7d1617efe85ac1",
          "sha256": "830047a4063ae30072d9b40867e84a97ba34039881ab35de3b4ccd42f6e7474a",
          "sha1": "fc8d0946ca2428f4339fadb04342f6b3a78c8776",
          "md5": "23ed18716f6673c1b662bebccafa0040"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.getnova.framework.legacy",
          "module": "nova-boot",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "net.getnova.framework.legacy",
          "module": "nova-json",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "net.getnova.framework.legacy",
          "module": "nova-network",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "nova-api-2.0.1.jar",
          "url": "nova-api-2.0.1.jar",
          "size": 54766,
          "sha512": "c9c4b9aeba0b3ea0f3f52b79089264d092c3ff1299014967cc47484a91fb9d2f571bd207376988d45fd2e896db2fe2214fdecfc2c5b265d2ab7d1617efe85ac1",
          "sha256": "830047a4063ae30072d9b40867e84a97ba34039881ab35de3b4ccd42f6e7474a",
          "sha1": "fc8d0946ca2428f4339fadb04342f6b3a78c8776",
          "md5": "23ed18716f6673c1b662bebccafa0040"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-api-2.0.1-javadoc.jar",
          "url": "nova-api-2.0.1-javadoc.jar",
          "size": 212766,
          "sha512": "96514d45fc8b9efee9c94dce99dc8f0c39091601e1d372b55a48bca1c7195490117702370b99cf49cd6edfd94e74378348dddd66f6f1c9aa5e3f19a4b43af09c",
          "sha256": "c1d2bb9babc2d225ffb92c751558187a75e54615b60df74b9ca3acde77749fe3",
          "sha1": "9b17a1cc613a5b5919c4fa30800bce862e556173",
          "md5": "a8ab962a8e4d9e56cb20f42933e5b2f1"
        }
      ]
    }
  ]
}
