{
  "formatVersion": "1.1",
  "component": {
    "group": "de.m4rc3l.nova",
    "module": "nova-data-jpa",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "nova-data-jpa-4.0.0.jar",
          "url": "nova-data-jpa-4.0.0.jar",
          "size": 16146,
          "sha512": "842715633f58bec0e9fbf0804b55071214812c2a172f7e90d37d4e55681beb97cbd558de65b36783c2fb55eafedd6f1b850f274cc14a2f7cb6738e4d2ba72634",
          "sha256": "57e7b5a2766ac1e9150be85515c3becd927bae052b653278e5d0bf25854e1b97",
          "sha1": "9039b569a7d8de12e9f94ef18553254542eaa600",
          "md5": "c0b6c1b26ca5d35a346b920a5ca53d6d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.4.1.Final"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "nova-data-jpa-4.0.0.jar",
          "url": "nova-data-jpa-4.0.0.jar",
          "size": 16146,
          "sha512": "842715633f58bec0e9fbf0804b55071214812c2a172f7e90d37d4e55681beb97cbd558de65b36783c2fb55eafedd6f1b850f274cc14a2f7cb6738e4d2ba72634",
          "sha256": "57e7b5a2766ac1e9150be85515c3becd927bae052b653278e5d0bf25854e1b97",
          "sha1": "9039b569a7d8de12e9f94ef18553254542eaa600",
          "md5": "c0b6c1b26ca5d35a346b920a5ca53d6d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-data-jpa-4.0.0-javadoc.jar",
          "url": "nova-data-jpa-4.0.0-javadoc.jar",
          "size": 87882,
          "sha512": "82411f0f58bc6d41269352d727e2c1612d20898a3a0ff25e6a9a3f86eadb881d5cb429a7c878275d0ff826c0a9b4fcef980cbe80262cadd71ee506d99a98842e",
          "sha256": "7a1e32f2223154b5907fac94f3e771648f3117d43bbc191220ed31d8699f2137",
          "sha1": "57dd885556011d1ad43e2bc2d6239e6f641211ba",
          "md5": "069b01431518855b76d61c1b8d9342fe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-data-jpa-4.0.0-sources.jar",
          "url": "nova-data-jpa-4.0.0-sources.jar",
          "size": 3447,
          "sha512": "fb6290d509a63861ce5bab193d1e62c917cf967365ad03851b1895443863401107569ff0685284e6a410bde7fead3f27c445bde31f89a1c341ec8b8789bdc4b3",
          "sha256": "9bedeea2cd639a2e66d3c9825b7e836e147a19b06fc3186c93d315c2cdf2d91f",
          "sha1": "c56a6599f5d3a39522cb2d7c3b0101c29f81fc20",
          "md5": "f9d9a6c9f880bed6bd6643c01f84a5a0"
        }
      ]
    }
  ]
}
