{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-cdn",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "vqhw3xnutbgw5jsc4m4ygtu7se"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-web",
          "version": {
            "requires": "edge"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-data-jpa",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-cdn-edge.jar",
          "url": "nova-cdn-edge.jar",
          "size": 23763,
          "sha512": "70d4db260b8d62a17dfa1adc27e97657afdf3f6be610dc52839decd984f3453f2bff548d5eebdce2cc27b3fecf94eb50cdeed007f7ec2c5a4fb5dd0f2e49555b",
          "sha256": "97fecc41eea64f6ced9534965e75e27a4e78a9426d511bffc76734c506dcb883",
          "sha1": "564565ccb98d64b3bb165b198b5b5661f1dff255",
          "md5": "a4f14262d3a8dbf8f9dec10ffd74c67c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-web",
          "version": {
            "requires": "edge"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-data-jpa",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-cdn-edge.jar",
          "url": "nova-cdn-edge.jar",
          "size": 23763,
          "sha512": "70d4db260b8d62a17dfa1adc27e97657afdf3f6be610dc52839decd984f3453f2bff548d5eebdce2cc27b3fecf94eb50cdeed007f7ec2c5a4fb5dd0f2e49555b",
          "sha256": "97fecc41eea64f6ced9534965e75e27a4e78a9426d511bffc76734c506dcb883",
          "sha1": "564565ccb98d64b3bb165b198b5b5661f1dff255",
          "md5": "a4f14262d3a8dbf8f9dec10ffd74c67c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-cdn-edge-javadoc.jar",
          "url": "nova-cdn-edge-javadoc.jar",
          "size": 414192,
          "sha512": "bb2790b555db654b94e10794d2aa99eaa31eac34fa56390a2c24d616a0f8306947235213ef7db90165927989b54bd6b96e0db19801f7e1a3c70cb8971536cf72",
          "sha256": "458270d3bdc53125b93fb35109e78a8711ff97ab800d8c12aafbd5621e265a2e",
          "sha1": "e7ec3a6d967731192e6365e28a4d201c73a8d641",
          "md5": "24bd37432f4f5fc6d83c4ff8882afdbf"
        }
      ]
    }
  ]
}
