{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-cdn",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "5zkrr62wrjh6jn5mxm7hljpp5u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-web",
          "version": {
            "requires": "edge"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-data-jpa",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-cdn-edge.jar",
          "url": "nova-cdn-edge.jar",
          "size": 23762,
          "sha512": "c0cda124caf5b69390e80c24c1d325d374a59a0e290f8f9d017db8698319a3935f8e2ce27af8834b8c1cbc877239591328f6746408e09b28aaaf7fcbfe65ad3d",
          "sha256": "864cbfeab81b42b4e76499eeb4e71d190bf554a79d548e71b37e54025008c117",
          "sha1": "4572eaf414b77796924ffdade050e2109fd8ebec",
          "md5": "0b0fec62cb32428fee6e23e18d99efb7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-web",
          "version": {
            "requires": "edge"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-data-jpa",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-cdn-edge.jar",
          "url": "nova-cdn-edge.jar",
          "size": 23762,
          "sha512": "c0cda124caf5b69390e80c24c1d325d374a59a0e290f8f9d017db8698319a3935f8e2ce27af8834b8c1cbc877239591328f6746408e09b28aaaf7fcbfe65ad3d",
          "sha256": "864cbfeab81b42b4e76499eeb4e71d190bf554a79d548e71b37e54025008c117",
          "sha1": "4572eaf414b77796924ffdade050e2109fd8ebec",
          "md5": "0b0fec62cb32428fee6e23e18d99efb7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-cdn-edge-javadoc.jar",
          "url": "nova-cdn-edge-javadoc.jar",
          "size": 414191,
          "sha512": "61c98d4356a183a4d35f4a92948fef8e0feb6f72521e0d1393cfd0802b3dec11437f408213f209e61e56b2cf41dbe94a11901d02581ac1cb7480a3fbb564be9b",
          "sha256": "a8d0e1ea4f7b25e6e8ba38703ccaa4723ce1ca68b56c7a970911d5397904c2c4",
          "sha1": "dd89342232db4e42909db9816d00adb1f99b1779",
          "md5": "100749bc69b141103a6432a701271962"
        }
      ]
    }
  ]
}
