{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-cdn",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "bwx6gknlz5bhrf2gfsmmar4kzq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-network",
          "version": {
            "requires": "edge"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-data-jpa",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-cdn-edge.jar",
          "url": "nova-cdn-edge.jar",
          "size": 12454,
          "sha512": "943eae76b5750a2b44b6c8b6d2494e589c7fb542c21e2bd359b717fec59350dedeb65ccb1c3bd3a312bfdb23430082a37c3c42f6dd6a6e55cf18cb84a1f7c428",
          "sha256": "5fac459e9760b8f0eb50071c21cd64e92f0f170146d029cab309cae4f8c70562",
          "sha1": "304b74c14f42737a0d42cff577b676d64313407c",
          "md5": "a348ce0d2de0d448e9e64f9eed9d0776"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-network",
          "version": {
            "requires": "edge"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-data-jpa",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-cdn-edge.jar",
          "url": "nova-cdn-edge.jar",
          "size": 12454,
          "sha512": "943eae76b5750a2b44b6c8b6d2494e589c7fb542c21e2bd359b717fec59350dedeb65ccb1c3bd3a312bfdb23430082a37c3c42f6dd6a6e55cf18cb84a1f7c428",
          "sha256": "5fac459e9760b8f0eb50071c21cd64e92f0f170146d029cab309cae4f8c70562",
          "sha1": "304b74c14f42737a0d42cff577b676d64313407c",
          "md5": "a348ce0d2de0d448e9e64f9eed9d0776"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-cdn-edge-javadoc.jar",
          "url": "nova-cdn-edge-javadoc.jar",
          "size": 125209,
          "sha512": "04956c2d996b424c75fdaf885453ca15f2884c1334c5b8fbd6a0a59ad2d15fd28f14f5b86e47d0019e850e9d51bc4cc05a76eb649e429f4c8fd08fe20b92f288",
          "sha256": "2db33099fb3183ec09f2ec4cc9c99bb3b8707acc9525dc1727015a15f0219ce3",
          "sha1": "0f8f12c690b48c63fa92629f89bcd5ec2bc96f0f",
          "md5": "38debe1bb0206cb2a0e0a4e637aacaac"
        }
      ]
    }
  ]
}
