{
  "formatVersion": "1.1",
  "component": {
    "group": "de.m4rc3l.nova",
    "module": "nova-influx",
    "version": "3.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "2.6.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "2.6.6"
          }
        }
      ],
      "files": [
        {
          "name": "nova-influx-3.0.5.jar",
          "url": "nova-influx-3.0.5.jar",
          "size": 44972,
          "sha512": "09e3bafaa70f15a21b62f3964931f5598ad5cb0dee8ec63f920eb0bb37b815493ac0d4e50b038ceea36fedc3935e6826efdbbd561a639a0025de236085948259",
          "sha256": "eb23e4848ef486214f1c953eefdfd3e783b29c703550f5f31bb74451d24ec2a7",
          "sha1": "5e6f0ea2a13cc3cb7bc453cc06498ec0dd9e6ce1",
          "md5": "bdd7b8de350184dd3546fc226a6fee12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "2.6.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "2.6.6"
          }
        }
      ],
      "files": [
        {
          "name": "nova-influx-3.0.5.jar",
          "url": "nova-influx-3.0.5.jar",
          "size": 44972,
          "sha512": "09e3bafaa70f15a21b62f3964931f5598ad5cb0dee8ec63f920eb0bb37b815493ac0d4e50b038ceea36fedc3935e6826efdbbd561a639a0025de236085948259",
          "sha256": "eb23e4848ef486214f1c953eefdfd3e783b29c703550f5f31bb74451d24ec2a7",
          "sha1": "5e6f0ea2a13cc3cb7bc453cc06498ec0dd9e6ce1",
          "md5": "bdd7b8de350184dd3546fc226a6fee12"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-influx-3.0.5-javadoc.jar",
          "url": "nova-influx-3.0.5-javadoc.jar",
          "size": 182569,
          "sha512": "885c7344d1ffa798bf906b3e285c2e581a50447d0dbe4e4bdc5bd2ad24778daca3586a1761c234fde40802c8dd22e4a51fc713ed4f13285cf155e8f75d454c58",
          "sha256": "729b04219197433e029a190205f214c53319e2d85c67275522f42dc520fe097f",
          "sha1": "6952b36f651be17f878a7c0f04a44f8c8b1515f1",
          "md5": "0e9ad35ed74fb55fd5558916d1f0ac56"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-influx-3.0.5-sources.jar",
          "url": "nova-influx-3.0.5-sources.jar",
          "size": 9618,
          "sha512": "f8df35b629ced59d39c8157146c80ae79b1ca5f72cd6c29ce44d7463bd96a564f9aca8801ba2435038584cb51551ebc9a0633762aa7d28a13d9d23f444c43493",
          "sha256": "abe37f80a8779a4ea5b32f077a8d0b683ba83af4e0a04e8b522292fc475c0e82",
          "sha1": "6c92ff1c33950306052a03e1e1a4f81c61e7f2aa",
          "md5": "41c1543f10b3e9e78cf565a0bebb539f"
        }
      ]
    }
  ]
}
