{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-api-rest",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "iaxtcaid4fgljcgeufcjsw5yoq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.4"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-api",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-api-rest-edge.jar",
          "url": "nova-api-rest-edge.jar",
          "size": 23154,
          "sha512": "3b10470ab88284365e5de65cabf448ee9cc8bbb730ca267510192e704fadd627c77c1856b8ea102d0ce1f8fa575d2e2fd9d0530acb1af0f32aeedebe9e635872",
          "sha256": "2e457a4302e05710134751ab9cef7a1a7f0cc3da717d846213c2436b8ef09a60",
          "sha1": "e5962289a9203d8444e7c7861aabbb129b1c8d81",
          "md5": "29d3ea27e9e18e3b586dedd8d448eb7d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.4"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-api",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-api-rest-edge.jar",
          "url": "nova-api-rest-edge.jar",
          "size": 23154,
          "sha512": "3b10470ab88284365e5de65cabf448ee9cc8bbb730ca267510192e704fadd627c77c1856b8ea102d0ce1f8fa575d2e2fd9d0530acb1af0f32aeedebe9e635872",
          "sha256": "2e457a4302e05710134751ab9cef7a1a7f0cc3da717d846213c2436b8ef09a60",
          "sha1": "e5962289a9203d8444e7c7861aabbb129b1c8d81",
          "md5": "29d3ea27e9e18e3b586dedd8d448eb7d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-api-rest-edge-javadoc.jar",
          "url": "nova-api-rest-edge-javadoc.jar",
          "size": 416420,
          "sha512": "cce0f8575a28524b671e0081942ac3f43ff1e8ad3300a27f60a7ab0b4bdaded442400a3355c8813f050acec065b7d04a295c8c65ced44c74e1b81b2dcad8702c",
          "sha256": "7dfc34b2279d95e862103a1c03f5c35ddc9e6788037da49d5ac5208d4b8bd7b8",
          "sha1": "75c475165e6cd12c154fe5a47cc491840111731d",
          "md5": "ce53a9481da6e53bbf543f8b86f1c2df"
        }
      ]
    }
  ]
}
