{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-api-rest",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "5zkrr62wrjh6jn5mxm7hljpp5u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.4"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-api",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-api-rest-edge.jar",
          "url": "nova-api-rest-edge.jar",
          "size": 23153,
          "sha512": "bb60ac0ae165b31d7b14428b1c2da655f261775307b6d086969f5de570acd1259267f5ae09fd89d88dc7f39d4ef0c77189347fbfb96e7b2c611a9577460f1edd",
          "sha256": "11653de75e6ee67029550987ee37f45558c52359e080b2542365652d382143ca",
          "sha1": "76e2aa7e0bbb136efaf9afad56dd4b92c72a595b",
          "md5": "9b6d2f9e3e594f834267678e855962e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.4"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-api",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-api-rest-edge.jar",
          "url": "nova-api-rest-edge.jar",
          "size": 23153,
          "sha512": "bb60ac0ae165b31d7b14428b1c2da655f261775307b6d086969f5de570acd1259267f5ae09fd89d88dc7f39d4ef0c77189347fbfb96e7b2c611a9577460f1edd",
          "sha256": "11653de75e6ee67029550987ee37f45558c52359e080b2542365652d382143ca",
          "sha1": "76e2aa7e0bbb136efaf9afad56dd4b92c72a595b",
          "md5": "9b6d2f9e3e594f834267678e855962e5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-api-rest-edge-javadoc.jar",
          "url": "nova-api-rest-edge-javadoc.jar",
          "size": 416424,
          "sha512": "9d8dde189e99a01ea42c6e4a372bf5d638ad14473c24022c443ffe51ef1cfb10581753bbea7afa03a3a3281816f831f569ccbc0b7e08469ec394508491f5cec9",
          "sha256": "f18a2878aa3174ca2bbe98b27513c31f2e8e67b12b5202fd90edfa3b8e82d421",
          "sha1": "514de33374ec2935f9341d9884f8cabc7b41adec",
          "md5": "5005bcd8ef1eb7bb834c673e55d171f1"
        }
      ]
    }
  ]
}
