{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-api-rest",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "fkkunofbyfc4bfm73lpezgqglu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.4"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-api",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-api-rest-edge.jar",
          "url": "nova-api-rest-edge.jar",
          "size": 23154,
          "sha512": "93db09bb4b80fe555b2f53dbfdee52905b0b95ccc744cc5a69eb1d0aab70b39cfe72b2dca484218e5ab57251d1281f245d0a2e18872ca1439ead4311e8c81e5d",
          "sha256": "5bd1806c4bea5c84deb8e23ad840d1ec1ae3066d8faf845cb3a0106a4bbd221d",
          "sha1": "44969d9aa0e3ee750b5792437658651592b6aa9f",
          "md5": "a283d817283c1a37312dc81d8607ca69"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.4"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-api",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-api-rest-edge.jar",
          "url": "nova-api-rest-edge.jar",
          "size": 23154,
          "sha512": "93db09bb4b80fe555b2f53dbfdee52905b0b95ccc744cc5a69eb1d0aab70b39cfe72b2dca484218e5ab57251d1281f245d0a2e18872ca1439ead4311e8c81e5d",
          "sha256": "5bd1806c4bea5c84deb8e23ad840d1ec1ae3066d8faf845cb3a0106a4bbd221d",
          "sha1": "44969d9aa0e3ee750b5792437658651592b6aa9f",
          "md5": "a283d817283c1a37312dc81d8607ca69"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-api-rest-edge-javadoc.jar",
          "url": "nova-api-rest-edge-javadoc.jar",
          "size": 416423,
          "sha512": "443e4acc6ecd646688e2b6c3fe38535fc891cbfae520de82fc63de253ba826fcece50145c51be35455b5dde98b2e6f1c52f7a35b869f0cf1cd0776ae34d33e82",
          "sha256": "674bbbb1f46156fabb9d51da14f47a28b4d389f46f10a0807938be4ab718f330",
          "sha1": "3c030ee39c2d3d5839a8e175d4e20a3c9b5e910a",
          "md5": "4e1770a6335395bbf7972039b1ef3d97"
        }
      ]
    }
  ]
}
