{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework.legacy",
    "module": "nova-data-jpa",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.getnova.framework.legacy",
          "module": "nova-data",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "net.getnova.framework.legacy",
          "module": "nova-json",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.3.4.RELEASE"
          },
          "excludes": [
            {
              "group": "org.aspectj",
              "module": "aspectjrt"
            }
          ]
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.4.27.Final"
          },
          "excludes": [
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.2.18"
          }
        }
      ],
      "files": [
        {
          "name": "nova-data-jpa-2.0.1.jar",
          "url": "nova-data-jpa-2.0.1.jar",
          "size": 8593,
          "sha512": "741b481aac6b36a71ac454fe0c8a50af659eba654694832b611d4185385c9e7407b447cac27862e19087d173659e01751b434504acc8a097616f83c1b9a5f41a",
          "sha256": "39e22d249786220589e1c58abd0266cea2ed5c9585c3bef9e5a0219fb2f5a637",
          "sha1": "4aa047869efb1407674de8d05422b2571567482c",
          "md5": "bd74c02bd63b8227c647f428fab2276f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.getnova.framework.legacy",
          "module": "nova-data",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "net.getnova.framework.legacy",
          "module": "nova-json",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.3.4.RELEASE"
          },
          "excludes": [
            {
              "group": "org.aspectj",
              "module": "aspectjrt"
            }
          ]
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.4.27.Final"
          },
          "excludes": [
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.2.18"
          }
        }
      ],
      "files": [
        {
          "name": "nova-data-jpa-2.0.1.jar",
          "url": "nova-data-jpa-2.0.1.jar",
          "size": 8593,
          "sha512": "741b481aac6b36a71ac454fe0c8a50af659eba654694832b611d4185385c9e7407b447cac27862e19087d173659e01751b434504acc8a097616f83c1b9a5f41a",
          "sha256": "39e22d249786220589e1c58abd0266cea2ed5c9585c3bef9e5a0219fb2f5a637",
          "sha1": "4aa047869efb1407674de8d05422b2571567482c",
          "md5": "bd74c02bd63b8227c647f428fab2276f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-data-jpa-2.0.1-javadoc.jar",
          "url": "nova-data-jpa-2.0.1-javadoc.jar",
          "size": 120126,
          "sha512": "21c37d31b4945dbeb9c22608e6f863613ce35f363c5bbde607600a9031f0a4c051254b7eb73fd3cc802e0c5cd088a5a0f134d108f3f62bf96d4fd9e7331bf97e",
          "sha256": "be872294ec0de731ee1aed34e66fd96583407f7262e229b3fb1e9011d6fa0fe1",
          "sha1": "edbf8f3b69c186a44f7de1ac388dc728ee01cc53",
          "md5": "b4d251d8c2e2799fc7d58a2df09322b4"
        }
      ]
    }
  ]
}
