{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-network",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "qd6xp3rztvh5pny2utekwipqxi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-reactor-netty",
          "version": {
            "requires": "2.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "nova-network-edge.jar",
          "url": "nova-network-edge.jar",
          "size": 35492,
          "sha512": "5454ba4d109d6ad83eec8705f9f26a508908e9572011dfd9245bb28618229f870ead628cc050f731a8e798a0e3e49d50f3e22d032611d70c79558651e4df244d",
          "sha256": "a700cd989f64ab67999187c1aafe9ee00bec9a76ce45311561a7f4b76812e2b0",
          "sha1": "59d032ba47995c55cb9dd20461e37c15312c3480",
          "md5": "ddbafe81d8f78d1d105d0e5be4733787"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-reactor-netty",
          "version": {
            "requires": "2.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "nova-network-edge.jar",
          "url": "nova-network-edge.jar",
          "size": 35492,
          "sha512": "5454ba4d109d6ad83eec8705f9f26a508908e9572011dfd9245bb28618229f870ead628cc050f731a8e798a0e3e49d50f3e22d032611d70c79558651e4df244d",
          "sha256": "a700cd989f64ab67999187c1aafe9ee00bec9a76ce45311561a7f4b76812e2b0",
          "sha1": "59d032ba47995c55cb9dd20461e37c15312c3480",
          "md5": "ddbafe81d8f78d1d105d0e5be4733787"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-network-edge-javadoc.jar",
          "url": "nova-network-edge-javadoc.jar",
          "size": 134670,
          "sha512": "2e508bf127a66ac563a297b36e1c6d1ecbabb197045ed336c7265e1915488eaba7ccfd53ae766e5849adb1e6fcbf8572426c43ab6c00d28914fb6932f7d6b7ce",
          "sha256": "6df6c9603492ea2164621988a4e58b5baa0a560560c0b27cafc86dbf717a02b9",
          "sha1": "f670052c82ef23aaf391060dd5634275d0fa4b75",
          "md5": "347930cf1ac006da2ed6b82a63b3b8ca"
        }
      ]
    }
  ]
}
