{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-network",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "nkitkmu5abglpahtld3fchsiuu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-reactor-netty",
          "version": {
            "requires": "2.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "nova-network-edge.jar",
          "url": "nova-network-edge.jar",
          "size": 35489,
          "sha512": "1200962bb4ecdbbfb848c409cc1086122b0b5e95e864db5023c4bcb357ca13b9c7e08f9d1e35ab2486e0e2554e0ddfb80099c7e3a783aec4236698bf303148d3",
          "sha256": "639029d49414c940bc34cb095084daf796ef1f5cd2b1152bd86202ab68ee7c1a",
          "sha1": "c5a36ec427e8a2cc9c831659a0633fc91c643595",
          "md5": "7ca6e5d2ece745ec9437abbe24aa88ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-reactor-netty",
          "version": {
            "requires": "2.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "nova-network-edge.jar",
          "url": "nova-network-edge.jar",
          "size": 35489,
          "sha512": "1200962bb4ecdbbfb848c409cc1086122b0b5e95e864db5023c4bcb357ca13b9c7e08f9d1e35ab2486e0e2554e0ddfb80099c7e3a783aec4236698bf303148d3",
          "sha256": "639029d49414c940bc34cb095084daf796ef1f5cd2b1152bd86202ab68ee7c1a",
          "sha1": "c5a36ec427e8a2cc9c831659a0633fc91c643595",
          "md5": "7ca6e5d2ece745ec9437abbe24aa88ca"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-network-edge-javadoc.jar",
          "url": "nova-network-edge-javadoc.jar",
          "size": 134668,
          "sha512": "a2ad96171a68e25aad035c959cbe3a448b08e54906ebc805f2a6831971acb35571a866f661d2997de7cf3f65f2119ac3f2ef2d4180e158aaf25702681035cd08",
          "sha256": "d0b130fa2cf6b34c33010565cc921f7063eb509f4efab5e2dab51d0792d13eee",
          "sha1": "e2af13019b99c16793f127653da962f5c3ec25fc",
          "md5": "63114f29db081e742a985bfe78cbe7eb"
        }
      ]
    }
  ]
}
