{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-network",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "zbalho3jyfckbj4nj6k5pfkfj4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-reactor-netty",
          "version": {
            "requires": "2.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "nova-network-edge.jar",
          "url": "nova-network-edge.jar",
          "size": 35327,
          "sha512": "d1d9b11f7247e6d5c098edea147d916beaddb0b180a185108a96189f8a4171a555d0cf56aa0820318f7692f896b8c15da21909f8c9f910ebb34f7f48df4476ba",
          "sha256": "c089bb2fff0cfd71c83f16af58b3cd17f7e3fe50240856fa8719eea51066e279",
          "sha1": "9b3c59d0b0a0d662c6637ce3495c7e216752006f",
          "md5": "2f8ad8ed7f1b69e5a2a2628caa7376dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-reactor-netty",
          "version": {
            "requires": "2.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "nova-network-edge.jar",
          "url": "nova-network-edge.jar",
          "size": 35327,
          "sha512": "d1d9b11f7247e6d5c098edea147d916beaddb0b180a185108a96189f8a4171a555d0cf56aa0820318f7692f896b8c15da21909f8c9f910ebb34f7f48df4476ba",
          "sha256": "c089bb2fff0cfd71c83f16af58b3cd17f7e3fe50240856fa8719eea51066e279",
          "sha1": "9b3c59d0b0a0d662c6637ce3495c7e216752006f",
          "md5": "2f8ad8ed7f1b69e5a2a2628caa7376dd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-network-edge-javadoc.jar",
          "url": "nova-network-edge-javadoc.jar",
          "size": 424307,
          "sha512": "31a023a09dd35f434b2f3491b9e9e6aac722487d212aa295cc1989cf500d7c23b4b113bbc8e73d36e55bf7a6195c70ec30f16bdf4e4f0b9c182f669fb883ba52",
          "sha256": "06179bfd2ae01ff8ddb6c2f1d8ea41d3f25ff3a62b73da11c2cc0aa90eca790c",
          "sha1": "89822132ffea08ed4fe37645dced29dbbc5a9559",
          "md5": "a1911a10df53230cf126dd00a805b327"
        }
      ]
    }
  ]
}
