{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework.legacy",
    "module": "nova-json",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.getnova.framework.legacy",
          "module": "nova-boot",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "nova-json-2.0.1.jar",
          "url": "nova-json-2.0.1.jar",
          "size": 12316,
          "sha512": "b291e4ac9e0e8b67d6601e96d706eeb8c35483c73c05f930db7f7f185a26dd27bc0b36704ce25c1fdbe6c49c4047584975b54137fded0cf537d9bb1dbeeb35c5",
          "sha256": "1a92b34ab7b9c7f3a9f151415fa391d7401e9cf1e4f55f8370cce843a2e3fbc9",
          "sha1": "89f23db2d929ffc9239244228facc474e0327114",
          "md5": "186ac75d69fd54384c4791efafe5d77b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.getnova.framework.legacy",
          "module": "nova-boot",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "nova-json-2.0.1.jar",
          "url": "nova-json-2.0.1.jar",
          "size": 12316,
          "sha512": "b291e4ac9e0e8b67d6601e96d706eeb8c35483c73c05f930db7f7f185a26dd27bc0b36704ce25c1fdbe6c49c4047584975b54137fded0cf537d9bb1dbeeb35c5",
          "sha256": "1a92b34ab7b9c7f3a9f151415fa391d7401e9cf1e4f55f8370cce843a2e3fbc9",
          "sha1": "89f23db2d929ffc9239244228facc474e0327114",
          "md5": "186ac75d69fd54384c4791efafe5d77b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-json-2.0.1-javadoc.jar",
          "url": "nova-json-2.0.1-javadoc.jar",
          "size": 137263,
          "sha512": "0b05b3e1af4e42d095f13f7ac8c6e1a1e3a988695420b11b00d3262ebc4d38f1db020bd8f8e6bb74f4d1a3c048be95a68e4f895b2b92aaee8c7099a0f006e895",
          "sha256": "bed33aaaa7c38bcbec902fcb755d1bbd555cb4f1f7b7a564b9349341b36a83a8",
          "sha1": "99516cfc9818778e8253d74bf9bc073add6b392a",
          "md5": "b61e8b84a8d0a7a4c756cbb1a26c4e07"
        }
      ]
    }
  ]
}
