{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-web",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "etplgg6ugrad7my6bf35r3hdia"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-core",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-web-edge.jar",
          "url": "nova-web-edge.jar",
          "size": 51942,
          "sha512": "0cd4c55b9e8a40c2fcd6cc281e4bc694d60656bea1b7cde9aed6c48ef166a19a50591d1f927cc6ffc64d503c0773dedad3ea1191475ff6882cbf3d8ba4431b50",
          "sha256": "2c876ecd1770bbca93d3e362b2e8cb70de5f1c2887970c75b769687fdae91722",
          "sha1": "cd26701b272f4dcdaf861650b44ddc22271d2b0f",
          "md5": "dc6ed2d1eee7accd0bf67129b0043769"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-core",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-web-edge.jar",
          "url": "nova-web-edge.jar",
          "size": 51942,
          "sha512": "0cd4c55b9e8a40c2fcd6cc281e4bc694d60656bea1b7cde9aed6c48ef166a19a50591d1f927cc6ffc64d503c0773dedad3ea1191475ff6882cbf3d8ba4431b50",
          "sha256": "2c876ecd1770bbca93d3e362b2e8cb70de5f1c2887970c75b769687fdae91722",
          "sha1": "cd26701b272f4dcdaf861650b44ddc22271d2b0f",
          "md5": "dc6ed2d1eee7accd0bf67129b0043769"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-web-edge-javadoc.jar",
          "url": "nova-web-edge-javadoc.jar",
          "size": 439383,
          "sha512": "71bbfbf4ef68dd66704760bd7ddc980c17b1f40061ad06d94e8f90cd520330720121b5ab69ef5aff301e43d5b5abdb8bd2f1556dc485e5b6dd1138b126289a32",
          "sha256": "c5d7642266071f0b92c42ab474db6746bf854394d6061665768e7ed436a63abd",
          "sha1": "0f38edb4d6213436ecc3e82b2fec8fddb6757242",
          "md5": "35a17bc4666376926bf4da7e4b57fc22"
        }
      ]
    }
  ]
}
