{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-web",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "5zkrr62wrjh6jn5mxm7hljpp5u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-core",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-web-edge.jar",
          "url": "nova-web-edge.jar",
          "size": 52027,
          "sha512": "083ef2de1a6f3350d9dde38f35dc0b8cda99840d561d6f9d2d205a50add65335926ab533072bd898fd23f2399f703efaf86fcd246045694b8b3802c24b081200",
          "sha256": "6b102664bc5664a019416d8ad480e1295eb0044517c0b2032be15880802ac940",
          "sha1": "a093b2a1e55a8bcc0a595b583fa6a74d07ccd804",
          "md5": "1c75541fdb564fb5dc09ef9e99f366d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-core",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-web-edge.jar",
          "url": "nova-web-edge.jar",
          "size": 52027,
          "sha512": "083ef2de1a6f3350d9dde38f35dc0b8cda99840d561d6f9d2d205a50add65335926ab533072bd898fd23f2399f703efaf86fcd246045694b8b3802c24b081200",
          "sha256": "6b102664bc5664a019416d8ad480e1295eb0044517c0b2032be15880802ac940",
          "sha1": "a093b2a1e55a8bcc0a595b583fa6a74d07ccd804",
          "md5": "1c75541fdb564fb5dc09ef9e99f366d3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-web-edge-javadoc.jar",
          "url": "nova-web-edge-javadoc.jar",
          "size": 439391,
          "sha512": "e088dbefa532535bd159fa4c05a7645e1b893474ce41a05617b8c728f19dea27e80944df5cb764ee5febb4d92523f4f7105596490e7bb144b316b9534c13351c",
          "sha256": "c2bd1d11ac1521823a02baf095b155c4df544b6653d5574cd2446fe70c11906b",
          "sha1": "c0c85c5f5290b96115bb26ada0dc45bde42368c5",
          "md5": "2e25a932212e45b4afbf11711fb61a48"
        }
      ]
    }
  ]
}
