{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-web",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6ohtp72qdfhn5jvcafyac3xcg4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-core",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-web-edge.jar",
          "url": "nova-web-edge.jar",
          "size": 52032,
          "sha512": "ec2dc50427517cf7d9fd0f136e5f0fe364931b7a7a0966ed7c52b061561ee08e1533784cf291f52dfdbe57c2aca47a0861533a89b172f24579c01eca7dbb098b",
          "sha256": "58aa5b323d215c1cfa36ba642f00282119bb5299a3c08b1e2cd1035137e04678",
          "sha1": "05949748693dbfae906cb7fc3347e14b80ada52d",
          "md5": "3fb0cf34520ab8f8b2d3300fefb0574d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-core",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-web-edge.jar",
          "url": "nova-web-edge.jar",
          "size": 52032,
          "sha512": "ec2dc50427517cf7d9fd0f136e5f0fe364931b7a7a0966ed7c52b061561ee08e1533784cf291f52dfdbe57c2aca47a0861533a89b172f24579c01eca7dbb098b",
          "sha256": "58aa5b323d215c1cfa36ba642f00282119bb5299a3c08b1e2cd1035137e04678",
          "sha1": "05949748693dbfae906cb7fc3347e14b80ada52d",
          "md5": "3fb0cf34520ab8f8b2d3300fefb0574d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-web-edge-javadoc.jar",
          "url": "nova-web-edge-javadoc.jar",
          "size": 439392,
          "sha512": "d8e319f3d688e1a0f3667103ff643c6df34708d2a57ef4848de7334b129ac23210b509d65755991171798285f236f110505ffa70e7a31be8ee27033c9600ebc9",
          "sha256": "977158b5c0f064b7f9ae144a82f1461ec5add466c9f56dadd3d0fd08c6e58485",
          "sha1": "85b1506e40e7cb350610a7b326a11fe9c0bda8ed",
          "md5": "2f063a1ffcec71c40ca3380363f1aafd"
        }
      ]
    }
  ]
}
