{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework.legacy",
    "module": "nova-starter",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nova-starter-2.0.1.jar",
          "url": "nova-starter-2.0.1.jar",
          "size": 1196,
          "sha512": "5575d2b4bae0a8b279faeea3ea8d4a83886a9b35db79ec16405c170a9daafda5392f665bdde4276d849525337d7927d376d56ae26b312679de7130004ca1da2b",
          "sha256": "a722c47e995bd216b5910566a3ef212688ed549e4d8a413aac24bb71b91e9347",
          "sha1": "3b2da948e2436222a046c387826e7578550796eb",
          "md5": "5c8b5eb94866b16f181a55a72a21d7d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.getnova.framework.legacy",
          "module": "nova-api",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "net.getnova.framework.legacy",
          "module": "nova-boot",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "net.getnova.framework.legacy",
          "module": "nova-cdn",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "net.getnova.framework.legacy",
          "module": "nova-data",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "net.getnova.framework.legacy",
          "module": "nova-data-jpa",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "net.getnova.framework.legacy",
          "module": "nova-json",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "net.getnova.framework.legacy",
          "module": "nova-network",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "nova-starter-2.0.1.jar",
          "url": "nova-starter-2.0.1.jar",
          "size": 1196,
          "sha512": "5575d2b4bae0a8b279faeea3ea8d4a83886a9b35db79ec16405c170a9daafda5392f665bdde4276d849525337d7927d376d56ae26b312679de7130004ca1da2b",
          "sha256": "a722c47e995bd216b5910566a3ef212688ed549e4d8a413aac24bb71b91e9347",
          "sha1": "3b2da948e2436222a046c387826e7578550796eb",
          "md5": "5c8b5eb94866b16f181a55a72a21d7d7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-starter-2.0.1-javadoc.jar",
          "url": "nova-starter-2.0.1-javadoc.jar",
          "size": 1129,
          "sha512": "6957b22e1a15fc71368c95235b3d65f6de43eec3327e538f04aadf6feb1645f125cf2acbcaea4a3aac81b7526a69535013649aa012705dd65263a5a147dd25dd",
          "sha256": "3434fa44a9072c800cbd6903fa5f0ae49a1247f416718566b513891a21e9ab17",
          "sha1": "8dcef6ed935406d1da467e1ccb6fc4548dac1182",
          "md5": "e9eb253278e114338321e2e1617fc0c7"
        }
      ]
    }
  ]
}
