{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-api-ws",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "7fb3qextrvbrbcfnqruzgctbre"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.4"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-api",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-api-ws-edge.jar",
          "url": "nova-api-ws-edge.jar",
          "size": 28290,
          "sha512": "1e1602b539fa383589e18a435705fb075125f2aa4f3de0049f4fa0da3597d43b117f9e064400ec35c0c95edee0a81447db7ca5ace581631db7f8ef97de09896d",
          "sha256": "3d6667ed4522a2d0819b71bf0cca5d9215de4ac73fb154f353241aff5ca69c71",
          "sha1": "dc51637c00ae90efcffa4b8ce0cb5ca05c091649",
          "md5": "b9a476830e524d76db5d3d74baee7e6b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.4"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-api",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-api-ws-edge.jar",
          "url": "nova-api-ws-edge.jar",
          "size": 28290,
          "sha512": "1e1602b539fa383589e18a435705fb075125f2aa4f3de0049f4fa0da3597d43b117f9e064400ec35c0c95edee0a81447db7ca5ace581631db7f8ef97de09896d",
          "sha256": "3d6667ed4522a2d0819b71bf0cca5d9215de4ac73fb154f353241aff5ca69c71",
          "sha1": "dc51637c00ae90efcffa4b8ce0cb5ca05c091649",
          "md5": "b9a476830e524d76db5d3d74baee7e6b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-api-ws-edge-javadoc.jar",
          "url": "nova-api-ws-edge-javadoc.jar",
          "size": 433983,
          "sha512": "9bedfa395015e81a8a00c2b80fb8c5ea8ad676b47af17ab11283ea5c6a607093adddb4898a923d2b1abd6a64f946d3679f33693d80445cdc10db0841e1aa3614",
          "sha256": "a3748779aea9fda4646442203df8f9e88ab0c376afea9df3c48b4bad8e35915c",
          "sha1": "9691f256d273546811a8e68ed10380caa1029f77",
          "md5": "e7569b454a0426051e9273150f511304"
        }
      ]
    }
  ]
}
