{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-api-ws",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "5zkrr62wrjh6jn5mxm7hljpp5u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.4"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-api",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-api-ws-edge.jar",
          "url": "nova-api-ws-edge.jar",
          "size": 28292,
          "sha512": "a8199022af65788322e5b16d2b2daaa3669356c7edf00da4e2a5b9a7717d4e153cc6c28b11ca84eea94affe62de333f4394b755bf6d63e6a71e808c10e8996d1",
          "sha256": "fdedd27cd632a05d028a07b58578ca13778395635590ddedc966226b15eb8858",
          "sha1": "640e5b55ba68ae7533e48897bb0cccbc58d56d6f",
          "md5": "230d4343f5a07c7e8a002976c94d2b29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.4"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-api",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-api-ws-edge.jar",
          "url": "nova-api-ws-edge.jar",
          "size": 28292,
          "sha512": "a8199022af65788322e5b16d2b2daaa3669356c7edf00da4e2a5b9a7717d4e153cc6c28b11ca84eea94affe62de333f4394b755bf6d63e6a71e808c10e8996d1",
          "sha256": "fdedd27cd632a05d028a07b58578ca13778395635590ddedc966226b15eb8858",
          "sha1": "640e5b55ba68ae7533e48897bb0cccbc58d56d6f",
          "md5": "230d4343f5a07c7e8a002976c94d2b29"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-api-ws-edge-javadoc.jar",
          "url": "nova-api-ws-edge-javadoc.jar",
          "size": 433984,
          "sha512": "ae7c90c069e3571ef5a0b5a4ceceef4decea513f67469d2530aa34e1dc486b6bf1c423c254e5de37603b06642dbe7744a9a7577bd1947e7a37776f5cf4830c6e",
          "sha256": "adef1565479c44011743a6d58f276ba6e9eb81f5b31982b24ee441a9e169c160",
          "sha1": "52a639df8b1514b3844402044fdd995afe73a5e3",
          "md5": "2866e06207d86d43a153eb2288f472d3"
        }
      ]
    }
  ]
}
