{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-api-ws",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6tovouee2vadvdjj4t2zxoieqi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.4"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-api",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-api-ws-edge.jar",
          "url": "nova-api-ws-edge.jar",
          "size": 28293,
          "sha512": "d51c60d9fb787cab127e66bf3911ec9074873a2ade320b7715586e7ebb21ad2ed211d7fc539d573f7771ca69f7a62a7a8d7feb20f1a7f4365780f3a8ceed7e04",
          "sha256": "52a63be497a0e5dfd5d1e7ac4cc291b87c67d1edced0e71d05f33f61f144c871",
          "sha1": "c922600554faab8820abd614b6e99d26424beb2a",
          "md5": "9d1f44c3d44468cd6be57de7c9022ec9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.4"
          }
        },
        {
          "group": "net.getnova.framework",
          "module": "nova-api",
          "version": {
            "requires": "edge"
          }
        }
      ],
      "files": [
        {
          "name": "nova-api-ws-edge.jar",
          "url": "nova-api-ws-edge.jar",
          "size": 28293,
          "sha512": "d51c60d9fb787cab127e66bf3911ec9074873a2ade320b7715586e7ebb21ad2ed211d7fc539d573f7771ca69f7a62a7a8d7feb20f1a7f4365780f3a8ceed7e04",
          "sha256": "52a63be497a0e5dfd5d1e7ac4cc291b87c67d1edced0e71d05f33f61f144c871",
          "sha1": "c922600554faab8820abd614b6e99d26424beb2a",
          "md5": "9d1f44c3d44468cd6be57de7c9022ec9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-api-ws-edge-javadoc.jar",
          "url": "nova-api-ws-edge-javadoc.jar",
          "size": 433986,
          "sha512": "fd86ad2fb390ebcdb974bdb90ec83e00fcc3ab4060721961881d1bb03418006656e5d9ef877a66605c04c8aa7740dba6a2932dcbb2d82f9537eea531442d05c9",
          "sha256": "f2947d0c0835c17cd7b69b3a7eac23e9d92c3abfc80b7b70059bde8b74f63539",
          "sha1": "bd3fbe9fffd4b0c555d002ae24d678eb70e69a20",
          "md5": "9eeb88b4e7e0cdaf618bcd04e127cc3c"
        }
      ]
    }
  ]
}
