{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework.legacy",
    "module": "nova-network",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.getnova.framework.legacy",
          "module": "nova-boot",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-bom",
          "version": {
            "requires": "2020.0.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-core",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-tcnative-boringssl-static",
          "version": {
            "requires": "2.0.36.Final"
          }
        }
      ],
      "files": [
        {
          "name": "nova-network-2.0.1.jar",
          "url": "nova-network-2.0.1.jar",
          "size": 37717,
          "sha512": "c3426afb0396026b348e6d38b30497264af85c34201c78acdca34c1eabe547f746c42e024c7d1673611f1672d42f5ce60f26a98109e3e14ee0eb0ff46efd7b1f",
          "sha256": "d1a8fe88e65e59b578d29962f5671cdf07a53665f68e8b53bbcc662d84472f0a",
          "sha1": "08f0098d50fb6625ba0d4bdd3ae64ca00835e6fc",
          "md5": "1d316db4ba973f873d519adf361390ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.getnova.framework.legacy",
          "module": "nova-boot",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-bom",
          "version": {
            "requires": "2020.0.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.4.2"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-core",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-tcnative-boringssl-static",
          "version": {
            "requires": "2.0.36.Final"
          }
        }
      ],
      "files": [
        {
          "name": "nova-network-2.0.1.jar",
          "url": "nova-network-2.0.1.jar",
          "size": 37717,
          "sha512": "c3426afb0396026b348e6d38b30497264af85c34201c78acdca34c1eabe547f746c42e024c7d1673611f1672d42f5ce60f26a98109e3e14ee0eb0ff46efd7b1f",
          "sha256": "d1a8fe88e65e59b578d29962f5671cdf07a53665f68e8b53bbcc662d84472f0a",
          "sha1": "08f0098d50fb6625ba0d4bdd3ae64ca00835e6fc",
          "md5": "1d316db4ba973f873d519adf361390ad"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-network-2.0.1-javadoc.jar",
          "url": "nova-network-2.0.1-javadoc.jar",
          "size": 135670,
          "sha512": "6b263de85ae2ab9de9f5279316103d5daee3c7295b52a515a66842c5534868d5f57a357ff8f95bdbd7cc112193b66a31264387d9ef8d9fb1ae21e6fa0cfcaf58",
          "sha256": "ee775382bb8a94985806ce5b5f0075de309b4ba366889d8b40fff2586f8c1291",
          "sha1": "2a23f6db4f928eeec3c5a308f37d0dd923839efd",
          "md5": "006c1c78b26aff235d14ce89d162e6d3"
        }
      ]
    }
  ]
}
