{
  "formatVersion": "1.1",
  "component": {
    "group": "de.m4rc3l.nova",
    "module": "nova-data-jpa",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "2.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "nova-data-jpa-edge.jar",
          "url": "nova-data-jpa-edge.jar",
          "size": 15982,
          "sha512": "32982ce1fe59fbfe4232e1d92838f493218e11322d948f5429e0444488998f124365ea35216fcfa053b04eb6aa607ed4cb7a69688bfcd9449b93318c04b589bf",
          "sha256": "822c9341fd829e4a9f40e0ef26f7e51cc21bd78b13314cd0fe73b813f420fc5f",
          "sha1": "1673f7a7716190a61b7c08c6c5a1dbf598640be8",
          "md5": "dadfe425ce10cbd2e58e43546ec166b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "2.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "nova-data-jpa-edge.jar",
          "url": "nova-data-jpa-edge.jar",
          "size": 15982,
          "sha512": "32982ce1fe59fbfe4232e1d92838f493218e11322d948f5429e0444488998f124365ea35216fcfa053b04eb6aa607ed4cb7a69688bfcd9449b93318c04b589bf",
          "sha256": "822c9341fd829e4a9f40e0ef26f7e51cc21bd78b13314cd0fe73b813f420fc5f",
          "sha1": "1673f7a7716190a61b7c08c6c5a1dbf598640be8",
          "md5": "dadfe425ce10cbd2e58e43546ec166b8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-data-jpa-edge-javadoc.jar",
          "url": "nova-data-jpa-edge-javadoc.jar",
          "size": 126550,
          "sha512": "dc7149370e1c188ce8d0f100e59c66e1137c0a7a8a40b0e8628d06297fdbdd35d408a6542fde7fe506f9868b648df041407e6cc77d831f641ff4b121a836997b",
          "sha256": "004276990b612e0a9afcc111d5826266e15a2fdc71efe3ec7f7d1fc8aac43755",
          "sha1": "a6240a7b1ec0cbf4322b35a615b2cea634038c69",
          "md5": "79511ec64b88a0fa2e2b2ebc4c76cd66"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-data-jpa-edge-sources.jar",
          "url": "nova-data-jpa-edge-sources.jar",
          "size": 3443,
          "sha512": "4109b9687620c2a1b8d73da0e14bf62099eaf28287b77f254f30af8e127ede5c76860e3a584baeda4ce05e0686e3c4a95e88c4def4e0b67053c21c2d95ae3584",
          "sha256": "dee2ce6af2b1d0fa583b5ca1f1be9fa6e24bf87351c265403a5925e57c438945",
          "sha1": "012f9fab4ac15b27d85674788440f98adcacbb99",
          "md5": "8a92cbff1d6de0e5e255af8ba5c9af7d"
        }
      ]
    }
  ]
}
