{
  "formatVersion": "1.1",
  "component": {
    "group": "de.m4rc3l.nova",
    "module": "nova-data-jpa",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "nova-data-jpa-edge.jar",
          "url": "nova-data-jpa-edge.jar",
          "size": 16144,
          "sha512": "6d566a2c632873e3e42b61ba074d3b8141e6cd4d7f19b5e7fb91c6a840ade006c43e0ec00502ca0b2b4f53148d03a05d8205f18ebd4a3e0814851ce484bccd26",
          "sha256": "095860085894da75dc9cd6d053134e3bf36915337cdf58189b74563477806479",
          "sha1": "e38001a33bcad984f814ca95b387b6b5e073a7e0",
          "md5": "e3572d293886f7b48facdb4ffd3ca3fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.4.1.Final"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "nova-data-jpa-edge.jar",
          "url": "nova-data-jpa-edge.jar",
          "size": 16144,
          "sha512": "6d566a2c632873e3e42b61ba074d3b8141e6cd4d7f19b5e7fb91c6a840ade006c43e0ec00502ca0b2b4f53148d03a05d8205f18ebd4a3e0814851ce484bccd26",
          "sha256": "095860085894da75dc9cd6d053134e3bf36915337cdf58189b74563477806479",
          "sha1": "e38001a33bcad984f814ca95b387b6b5e073a7e0",
          "md5": "e3572d293886f7b48facdb4ffd3ca3fd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-data-jpa-edge-javadoc.jar",
          "url": "nova-data-jpa-edge-javadoc.jar",
          "size": 87851,
          "sha512": "e4b17cc21e25cebe132cd774f4205b25362ff5823428d15a3717f9142101043003a93eba65afc6765e18e2f6c92e1a2883e440f07763353f083aace9764a74e7",
          "sha256": "24f960fbc58236558a39e569dfd16fac58f25e4df1957b7349933c59a7f0329c",
          "sha1": "ba8c55e7c424652c11e277322e02bf1927ce6174",
          "md5": "6dacdb8e18ca8b33c1ce8b2932fab919"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-data-jpa-edge-sources.jar",
          "url": "nova-data-jpa-edge-sources.jar",
          "size": 3444,
          "sha512": "1c4d46fb1b94eb85693dbfe41df9fdf667e0b1078b6bac485f39322af07c7ee61ee0ab3907dcb211c6f9ff73292285a90f62c9c7231b8c222ca0097627ae5de8",
          "sha256": "df9407025cebc6314384b21d5c993fb75de815be35cf11912817c94ec3c1365a",
          "sha1": "364e25da222e2ecb1c42b2f59a4c462e62191572",
          "md5": "2bd20ba5fed1697a4c5c03378298a578"
        }
      ]
    }
  ]
}
