{
  "formatVersion": "1.1",
  "component": {
    "group": "de.m4rc3l.nova",
    "module": "nova-data-jpa",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "nova-data-jpa-edge.jar",
          "url": "nova-data-jpa-edge.jar",
          "size": 16207,
          "sha512": "d12f5dbd463a501972a62bd9b8eca3c10da4e19393376509ef9864574c6db7bb4d7be27798a4ea458f0ebb52a6f0e74707bb185d46f86c54d8db6e79e0b0b969",
          "sha256": "fb51268af56184627f5f0672df81f74f344872fd326132ab4dceafae1f21e885",
          "sha1": "2b5ab6dfbf468b8c8f07fd56e7c48f311f315052",
          "md5": "defdb2ee70a5627acce1cdf7c97f2872"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.4.4.Final"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "nova-data-jpa-edge.jar",
          "url": "nova-data-jpa-edge.jar",
          "size": 16207,
          "sha512": "d12f5dbd463a501972a62bd9b8eca3c10da4e19393376509ef9864574c6db7bb4d7be27798a4ea458f0ebb52a6f0e74707bb185d46f86c54d8db6e79e0b0b969",
          "sha256": "fb51268af56184627f5f0672df81f74f344872fd326132ab4dceafae1f21e885",
          "sha1": "2b5ab6dfbf468b8c8f07fd56e7c48f311f315052",
          "md5": "defdb2ee70a5627acce1cdf7c97f2872"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-data-jpa-edge-javadoc.jar",
          "url": "nova-data-jpa-edge-javadoc.jar",
          "size": 87854,
          "sha512": "6448f1f0ce6d677c7c9d7a76e6b2bc7878441eaa09b63114ecd91eea2018cb01536a781189fb1b83654d4226c520115f8787dea274a6674cbd8925ecf12f216a",
          "sha256": "a78b5277e84d5c15669e282ea8eb5ef6687952afefa8c72efca9b92018a85273",
          "sha1": "d3a8d075c65024c5020733cfd674b5cdf1c79bfa",
          "md5": "7376245ae9fa9565f23b3ffad1745c75"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-data-jpa-edge-sources.jar",
          "url": "nova-data-jpa-edge-sources.jar",
          "size": 3447,
          "sha512": "8a19945e8d4aa589b82a11036a3fe70c7cd4a403753524908c38a693223928493400a3487fd40893ba97a5a7b27b600df3850110af41fa82244cb70da5008791",
          "sha256": "47a69cdde82f2efdb66dd894a8e78fbeed9b72939852ba3adb415d03896fb35f",
          "sha1": "5a69fe0e0a8e72bad609acd7f20d607beb53f738",
          "md5": "290211ac34dacb894da86b8dd5cee41f"
        }
      ]
    }
  ]
}
