{
  "formatVersion": "1.1",
  "component": {
    "group": "de.m4rc3l.nova",
    "module": "nova-influx",
    "version": "3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "2.6.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "2.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "nova-influx-3.0.3.jar",
          "url": "nova-influx-3.0.3.jar",
          "size": 44877,
          "sha512": "47499bc33f9e4d5f8ea2476fa34e5bf3a9790600a35799f92f4fe7f10f421a67e6ba94aeb04a3da77c2b99aebd23dd5946ea7cc892431a40f4062899b9c4d7da",
          "sha256": "2bfd075ce5bd7068640d06690d018e5fbe972527d13728fb874520c68c3d3e25",
          "sha1": "6cc456357ab4639e2ffec6776c0e978bb87d798b",
          "md5": "2153da2b81065d499d6bb89d58d4edc0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "2.6.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "2.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "nova-influx-3.0.3.jar",
          "url": "nova-influx-3.0.3.jar",
          "size": 44877,
          "sha512": "47499bc33f9e4d5f8ea2476fa34e5bf3a9790600a35799f92f4fe7f10f421a67e6ba94aeb04a3da77c2b99aebd23dd5946ea7cc892431a40f4062899b9c4d7da",
          "sha256": "2bfd075ce5bd7068640d06690d018e5fbe972527d13728fb874520c68c3d3e25",
          "sha1": "6cc456357ab4639e2ffec6776c0e978bb87d798b",
          "md5": "2153da2b81065d499d6bb89d58d4edc0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-influx-3.0.3-javadoc.jar",
          "url": "nova-influx-3.0.3-javadoc.jar",
          "size": 177771,
          "sha512": "fb6cd547991f3bd914f212846382d831e9dc4a99b7dbf6a190b21b340858ecd3213d7530ff9953d93e59b500455f15089a3ba8159067a1ba47aac295e1492a97",
          "sha256": "0a3b036e37d75660e340efa8affc05fb94c0511eb4e15a37e30871c55b27df71",
          "sha1": "847cc09a90628512d09de044beb5a057ba672e37",
          "md5": "28d461a211ec4e78e42106430dd67470"
        }
      ]
    }
  ]
}
