{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework.legacy",
    "module": "nova-boot",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-logback",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-framework-bom",
          "version": {
            "requires": "5.3.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.3"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "nova-boot-2.0.1.jar",
          "url": "nova-boot-2.0.1.jar",
          "size": 31448,
          "sha512": "264ea983922ed0b3c85929e481667c11ffa6abfa5251cadc5b3fcd1c6ec38a436da6c173c5786734381e37e18321bd20667c94f62daef253851e2f5b456f2243",
          "sha256": "eeae34341f506878df6465f4fd1d858ea48169e307f036b4f198008e66376985",
          "sha1": "d4859586983e60c0043d8ab031749105d7ef6dcb",
          "md5": "5ab7bb6da42a0f3c5ed6cd806bff4e97"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-logback",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-framework-bom",
          "version": {
            "requires": "5.3.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.3"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "nova-boot-2.0.1.jar",
          "url": "nova-boot-2.0.1.jar",
          "size": 31448,
          "sha512": "264ea983922ed0b3c85929e481667c11ffa6abfa5251cadc5b3fcd1c6ec38a436da6c173c5786734381e37e18321bd20667c94f62daef253851e2f5b456f2243",
          "sha256": "eeae34341f506878df6465f4fd1d858ea48169e307f036b4f198008e66376985",
          "sha1": "d4859586983e60c0043d8ab031749105d7ef6dcb",
          "md5": "5ab7bb6da42a0f3c5ed6cd806bff4e97"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-boot-2.0.1-javadoc.jar",
          "url": "nova-boot-2.0.1-javadoc.jar",
          "size": 165484,
          "sha512": "318ce0b031716fe433d39bdb4afa8617c3a4eac5f7ea2c14af874953e2e5ccd479269bef9e3e09fcb3fd9234a57625ccfd1d4d9f6d3751e5c1868870979ee0fb",
          "sha256": "71bd3367efcef88b69262b8b34f37dc666e536635d3ee5c5a9480702a6eede46",
          "sha1": "7be3fe70a9e1cfad0da5f46ab8f13f181ee171d3",
          "md5": "e67ab74813c12bfccd439bd265336975"
        }
      ]
    }
  ]
}
