{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-data-jpa",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "2.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "nova-data-jpa-edge.jar",
          "url": "nova-data-jpa-edge.jar",
          "size": 15987,
          "sha512": "ae21f05e2980e41fb5cebc9e728d2bb4be50b35c4cb5504ed42ffc9372e1a617d7b870784f0d1dc81f5987307a8035f098ecc46624a3f4cb54a885573e408335",
          "sha256": "06dce1ae7bc41ec8c1f0e71a09c434a19f5540def0991cec39fc8379af5dd222",
          "sha1": "1befe0adccff8ed1d74c0c3dd8b24c0a40558e30",
          "md5": "f2d60fb7bfdc4841aea2ac14c0557bea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "2.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "nova-data-jpa-edge.jar",
          "url": "nova-data-jpa-edge.jar",
          "size": 15987,
          "sha512": "ae21f05e2980e41fb5cebc9e728d2bb4be50b35c4cb5504ed42ffc9372e1a617d7b870784f0d1dc81f5987307a8035f098ecc46624a3f4cb54a885573e408335",
          "sha256": "06dce1ae7bc41ec8c1f0e71a09c434a19f5540def0991cec39fc8379af5dd222",
          "sha1": "1befe0adccff8ed1d74c0c3dd8b24c0a40558e30",
          "md5": "f2d60fb7bfdc4841aea2ac14c0557bea"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-data-jpa-edge-javadoc.jar",
          "url": "nova-data-jpa-edge-javadoc.jar",
          "size": 400721,
          "sha512": "168c1af8245c570d70d4d80fddf7ecc5f68772cc76d79fb0d88936166edad7a77c51e2aad607d094c57e6abd7648b31934797aecdbcfccb477ff73fce3bac243",
          "sha256": "6bdb7b3654eb9add2f1839cee64eb5fc608c0671a3b8ee364b9e9e26d4964092",
          "sha1": "23b4997dbb8c4ddccc7a8a6c545f6b604277a764",
          "md5": "8192664ffbad00031e2ba1d3a84c32a6"
        }
      ]
    }
  ]
}
