{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-data-jpa",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "2.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "nova-data-jpa-edge.jar",
          "url": "nova-data-jpa-edge.jar",
          "size": 15991,
          "sha512": "928af8df0fd3d252ff7af87b81fd8e2f389b7ccf6a4e5172c66019f4acaf8a782d256e69ffe7735ca44d3569513c9e9bb29919ddb75d7cef816b62b1e4191749",
          "sha256": "5eb89fb1a3daf677970c347c9b85efb88714d6b0a9b9215a0307abee4caf2203",
          "sha1": "6210c6dc15c53c5f7014425c1eca9276c32dc99a",
          "md5": "530aa790e5ec0022af59695b1bcec02f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "2.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "nova-data-jpa-edge.jar",
          "url": "nova-data-jpa-edge.jar",
          "size": 15991,
          "sha512": "928af8df0fd3d252ff7af87b81fd8e2f389b7ccf6a4e5172c66019f4acaf8a782d256e69ffe7735ca44d3569513c9e9bb29919ddb75d7cef816b62b1e4191749",
          "sha256": "5eb89fb1a3daf677970c347c9b85efb88714d6b0a9b9215a0307abee4caf2203",
          "sha1": "6210c6dc15c53c5f7014425c1eca9276c32dc99a",
          "md5": "530aa790e5ec0022af59695b1bcec02f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-data-jpa-edge-javadoc.jar",
          "url": "nova-data-jpa-edge-javadoc.jar",
          "size": 400732,
          "sha512": "005c61f77337ad8cd2f4b7f549434b00b4f9c5e8c49ae6129bd38d252345d23ed23e2fd25badd8def07c06978c41927c12d0dc7cfa60217b0039067dfe14900b",
          "sha256": "c2e9d2573df6e9670acd7f6fa36ccdecce126b7f31bb0d63248f7b9670434c2f",
          "sha1": "c77edaf98d6d387b40c582895d0c6a2bce4b05a4",
          "md5": "6df8e54c8ce762df18b2f06a507b65e7"
        }
      ]
    }
  ]
}
