{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-data-jpa",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "2.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "nova-data-jpa-edge.jar",
          "url": "nova-data-jpa-edge.jar",
          "size": 15992,
          "sha512": "79bac7a33fefcdc311793b435d78420a2f823ca82bdb63578d74730f47837f345d2dec2461041033d62995ee94ca5bee4c113c89ed75de66cc2c3fc2426ee6b7",
          "sha256": "06a49a8dbae58d8a807e0e9230c4a47ca3cca1b3cfbf53e878176e260c751b5f",
          "sha1": "734ff82d13d215206e4367191a61a0ba542eddc8",
          "md5": "4c0a042d775abe4693f5d335140ebc0a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "2.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "nova-data-jpa-edge.jar",
          "url": "nova-data-jpa-edge.jar",
          "size": 15992,
          "sha512": "79bac7a33fefcdc311793b435d78420a2f823ca82bdb63578d74730f47837f345d2dec2461041033d62995ee94ca5bee4c113c89ed75de66cc2c3fc2426ee6b7",
          "sha256": "06a49a8dbae58d8a807e0e9230c4a47ca3cca1b3cfbf53e878176e260c751b5f",
          "sha1": "734ff82d13d215206e4367191a61a0ba542eddc8",
          "md5": "4c0a042d775abe4693f5d335140ebc0a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-data-jpa-edge-javadoc.jar",
          "url": "nova-data-jpa-edge-javadoc.jar",
          "size": 400724,
          "sha512": "346ef5d6c764147fe8bbfd5f0a80793034c845cc451ca63adb268115c1ef28c485b33348abe6a4adc10e6243d3be020649e50aec32d02af33fed32ecfe216fa5",
          "sha256": "6eabf900bd656fbec74874b39a7a9105f17f5d4adc9cab20088ea81771475dc4",
          "sha1": "a2bf3dcf9a216df1e86090e6ba4a24347f8e563a",
          "md5": "44953e5d0fecfcfae7f9be44c36c67a2"
        }
      ]
    }
  ]
}
