{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-core",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.4"
          }
        }
      ],
      "files": [
        {
          "name": "nova-core-edge.jar",
          "url": "nova-core-edge.jar",
          "size": 16040,
          "sha512": "71adec04edd5705360f733ba9bb60ab0935bfb26036109802d0bf0e6f3e9b8ba429c1364c421e5a82bc760d6c441e05c195f11729085bafa7283c4b012f2e8de",
          "sha256": "5fb24ae7682351658a2e0cc05337edd155eb8e6ecbc22ab187d14bbc08715fee",
          "sha1": "955492ec1eba51a956cb38e12bb7da36e9b0cb08",
          "md5": "079d3cdd69d04ba8f6c9699a08a6d6d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.4"
          }
        }
      ],
      "files": [
        {
          "name": "nova-core-edge.jar",
          "url": "nova-core-edge.jar",
          "size": 16040,
          "sha512": "71adec04edd5705360f733ba9bb60ab0935bfb26036109802d0bf0e6f3e9b8ba429c1364c421e5a82bc760d6c441e05c195f11729085bafa7283c4b012f2e8de",
          "sha256": "5fb24ae7682351658a2e0cc05337edd155eb8e6ecbc22ab187d14bbc08715fee",
          "sha1": "955492ec1eba51a956cb38e12bb7da36e9b0cb08",
          "md5": "079d3cdd69d04ba8f6c9699a08a6d6d9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-core-edge-javadoc.jar",
          "url": "nova-core-edge-javadoc.jar",
          "size": 403418,
          "sha512": "009c5d0e09115a5f344dd25fae19aa2764d01673e3d6f1594342a3b038e69743829caae50deecd74e44f33ebe6ca59e714ede0e626272b9bd1fa46de9ae32e54",
          "sha256": "f2b73283474f9980b3a792b52edf8b40f7368c90ec8fc84e1e5de9dbba74e55f",
          "sha1": "00c5cb50ae0b34610a1dd836de61e6e2679e5654",
          "md5": "a382f24bb573f935c4f7bbd76b6442d6"
        }
      ]
    }
  ]
}
