{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-core",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.4"
          }
        }
      ],
      "files": [
        {
          "name": "nova-core-edge.jar",
          "url": "nova-core-edge.jar",
          "size": 42691,
          "sha512": "56f92963de095065be73428e5dea04f5af7aded558828e9a2c76eb0c553ebf6879b6a3df805e4c3ef27ba2c23e796b939bb5a6e951ed6f69f340743762dd4010",
          "sha256": "ffe15f46ac7a18ea6e71c49a918779478c8bff66060766d267a1ab60a4bc46c6",
          "sha1": "1b65dc90b3856ff00db3f107c1f9efa561a71f7d",
          "md5": "3fefbad3c3a7b43075a294b87d1feac0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.4.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.4"
          }
        }
      ],
      "files": [
        {
          "name": "nova-core-edge.jar",
          "url": "nova-core-edge.jar",
          "size": 42691,
          "sha512": "56f92963de095065be73428e5dea04f5af7aded558828e9a2c76eb0c553ebf6879b6a3df805e4c3ef27ba2c23e796b939bb5a6e951ed6f69f340743762dd4010",
          "sha256": "ffe15f46ac7a18ea6e71c49a918779478c8bff66060766d267a1ab60a4bc46c6",
          "sha1": "1b65dc90b3856ff00db3f107c1f9efa561a71f7d",
          "md5": "3fefbad3c3a7b43075a294b87d1feac0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-core-edge-javadoc.jar",
          "url": "nova-core-edge-javadoc.jar",
          "size": 491732,
          "sha512": "d64146a6a6429699ee64dc2378194e635b8e1da250fb059cb13546f1b3386dc8bd7c69f7bd938762ab64b7eeecfed7172f05e68036513c7238aaef73f5c9decb",
          "sha256": "bc2c05aae59c8488f13164ae864b992c842b52f41379ce4145204352de541c4a",
          "sha1": "df79dda23d6a03f9f02c57e2809d48397a64d674",
          "md5": "3bb056641f6c7658527f678998a8c3ef"
        }
      ]
    }
  ]
}
