{
  "formatVersion": "1.1",
  "component": {
    "group": "net.getnova.framework",
    "module": "nova-core",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "fkkunofbyfc4bfm73lpezgqglu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "5.3.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.4"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "nova-core-edge.jar",
          "url": "nova-core-edge.jar",
          "size": 19139,
          "sha512": "644f17407e9d51c6f7a5fae47d6d8f221afecd1f0c3040a1edf0dbd8f42a76ceb37c0a78219404a346fd214d1f49a757a518bd8eb70931ffa16beb83a243523c",
          "sha256": "bda81be9eec29bb74f4b39beb2c01c68d42d2722f9254011ca1a414e955f2128",
          "sha1": "101da96e30b7be0c530ccc1e13bd815b2dc716bc",
          "md5": "dbee786497e5440af207cfc0d229107a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.4.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "5.3.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.4"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "nova-core-edge.jar",
          "url": "nova-core-edge.jar",
          "size": 19139,
          "sha512": "644f17407e9d51c6f7a5fae47d6d8f221afecd1f0c3040a1edf0dbd8f42a76ceb37c0a78219404a346fd214d1f49a757a518bd8eb70931ffa16beb83a243523c",
          "sha256": "bda81be9eec29bb74f4b39beb2c01c68d42d2722f9254011ca1a414e955f2128",
          "sha1": "101da96e30b7be0c530ccc1e13bd815b2dc716bc",
          "md5": "dbee786497e5440af207cfc0d229107a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-core-edge-javadoc.jar",
          "url": "nova-core-edge-javadoc.jar",
          "size": 409655,
          "sha512": "efa02cd248d98f39778976cab444dfef73543603687535977e1b4f873ee2296556b4293f09064808eb32f853aad37e251e5a63fad5927955500230226d166b55",
          "sha256": "9a9498dced19b5323dab1b691b91c9e6832d625700981b67a4e229c20d68f78d",
          "sha1": "45f5673dd49d1de97055f7d57e473488c2331e4c",
          "md5": "54a3ed24fb2ea7fcaff0d372cfd12fb4"
        }
      ]
    }
  ]
}
